/**
 * Catch-all supervisor entity-slug route.
 *
 * Defense-in-depth fix for the recurring "page blanche" bug reported by
 * supervisors of OMS-style entities (MIN_COMERCIO, MIN_HACIENDA, AYUNTAMIENTO,
 * CAMARA, etc.):
 *
 * Some menu_config rows in the database — both legacy ones from migration 306
 * and ones generated by the dynamic workflow_menu_mapping engine — point at
 * `/dashboard/supervisor/<entity-slug>` (e.g. `/dashboard/supervisor/min-comercio`).
 * The frontend never shipped per-entity supervisor pages, so the user lands
 * on a blank screen.
 *
 * Migration 332 rewrote the affected `roles.menu_config` rows toward
 * `/dashboard/supervisor/entity-dashboard`, but two failure modes can revive
 * the issue:
 *   - the migration not being applied in a given environment (cache, schema
 *     tracking gap, manual edit by an admin);
 *   - the dynamic menu generator producing the same slug shape from
 *     `entities.workflow_codes` lookups.
 *
 * Rather than chasing every menu_config source, this route catches every
 * unknown supervisor sub-slug and redirects to the existing generic
 * entity-dashboard page. Static sibling routes (team, escalations, oms,
 * reports, inspections, companies, assignments, entity-dashboard) take
 * precedence in Next.js routing, so this fallback NEVER shadows a real page.
 *
 * Reserved guard: known siblings short-circuit a notFound() so any future
 * route accidentally added here surfaces a 404 instead of a silent redirect
 * that would mask the bug.
 */

import { redirect, notFound } from 'next/navigation';

const KNOWN_SUPERVISOR_SUBROUTES = new Set([
  'team',
  'escalations',
  'assignments',
  'oms',
  'reports',
  'inspections',
  'companies',
  'entity-dashboard',
]);

export default async function SupervisorEntityFallbackPage({
  params,
}: {
  params: Promise<{ locale: string; entity: string }>;
}) {
  const { locale, entity } = await params;

  // Defensive guard: if a real sibling somehow leaks into this catch-all
  // (mis-configured Next.js trie, build artefact race), surface a 404 so
  // the bug is loud rather than silently redirecting and hiding the cause.
  if (KNOWN_SUPERVISOR_SUBROUTES.has(entity)) {
    notFound();
  }

  redirect(`/${locale}/dashboard/supervisor/entity-dashboard`);
}
