/**
 * TaxasGE Mobile - Generated Chatbot FAQs
 *
 * Auto-generated from generate-faqs-from-seed.ts
 * Generated on: 2025-11-07T00:38:59.170Z
 * Total FAQs: 60
 */

import { ChatbotFAQ } from '../../types/chatbot.types';

export const GENERATED_FAQS: Omit<ChatbotFAQ, 'created_at' | 'updated_at'>[] = [
  {
    "id": "faq-service-001",
    "question_pattern": "(pasaporte|passport|passeport|renovar pasaporte|nuevo pasaporte)",
    "intent": "get_general_info",
    "response_es": "📋 **Pasaporte**\n\n💰 **Costos:**\n• Expedición: 50,000 XAF\n• Renovación: 40,000 XAF\n\n📄 **Descripción:**\nExpedición y renovación de pasaportes para ciudadanos de Guinea Ecuatorial\n\n⏱️ Plazo de procesamiento: 15 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Passeport**\n\n💰 **Coûts:**\n• Expédition: 50,000 XAF\n• Renouvellement: 40,000 XAF\n\n📄 **Description:**\nDélivrance et renouvellement de passeports pour les citoyens de Guinée équatoriale\n\n⏱️ Délai de traitement: 15 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Passport**\n\n💰 **Costs:**\n• Expedition: 50,000 XAF\n• Renewal: 40,000 XAF\n\n📄 **Description:**\nIssuance and renewal of passports for citizens of Equatorial Guinea\n\n⏱️ Processing time: 15 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"pasaporte\",\"passport\",\"passeport\",\"renovar pasaporte\",\"nuevo pasaporte\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-002",
    "question_pattern": "(visa|visado|visa turistico|visa trabajo|tourist visa|work visa)",
    "intent": "get_general_info",
    "response_es": "📋 **Visa**\n\n💰 **Costos:**\n• Expedición: 30,000 XAF\n\n\n📄 **Descripción:**\nSolicitud de visa para entrada a Guinea Ecuatorial (turismo, trabajo, negocios)\n\n⏱️ Plazo de procesamiento: 7 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Visa**\n\n💰 **Coûts:**\n• Expédition: 30,000 XAF\n\n\n📄 **Description:**\nDemande de visa pour l'entrée en Guinée équatoriale (tourisme, travail, affaires)\n\n⏱️ Délai de traitement: 7 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Visa**\n\n💰 **Costs:**\n• Expedition: 30,000 XAF\n\n\n📄 **Description:**\nVisa application for entry to Equatorial Guinea (tourism, work, business)\n\n⏱️ Processing time: 7 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"visa\",\"visado\",\"visa turistico\",\"visa trabajo\",\"tourist visa\",\"work visa\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-003",
    "question_pattern": "(licencia conducir|permis de conduire|driver's license|carnet de conducir|license)",
    "intent": "get_general_info",
    "response_es": "📋 **Licencia de Conducir**\n\n💰 **Costos:**\n• Expedición: 25,000 XAF\n• Renovación: 20,000 XAF\n\n📄 **Descripción:**\nExpedición y renovación de licencia de conducir\n\n⏱️ Plazo de procesamiento: 10 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Permis de Conduire**\n\n💰 **Coûts:**\n• Expédition: 25,000 XAF\n• Renouvellement: 20,000 XAF\n\n📄 **Description:**\nDélivrance et renouvellement du permis de conduire\n\n⏱️ Délai de traitement: 10 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Driver's License**\n\n💰 **Costs:**\n• Expedition: 25,000 XAF\n• Renewal: 20,000 XAF\n\n📄 **Description:**\nIssuance and renewal of driver's license\n\n⏱️ Processing time: 10 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"licencia conducir\",\"permis de conduire\",\"driver's license\",\"carnet de conducir\",\"license\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-004",
    "question_pattern": "(dni|cedula|identidad|identity card|carte d'identité|documento identidad)",
    "intent": "get_general_info",
    "response_es": "📋 **DNI - Documento Nacional de Identidad**\n\n💰 **Costos:**\n• Expedición: 15,000 XAF\n• Renovación: 12,000 XAF\n\n📄 **Descripción:**\nExpedición y renovación del Documento Nacional de Identidad (DNI)\n\n⏱️ Plazo de procesamiento: 7 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **DNI - Document National d'Identité**\n\n💰 **Coûts:**\n• Expédition: 15,000 XAF\n• Renouvellement: 12,000 XAF\n\n📄 **Description:**\nDélivrance et renouvellement du Document National d'Identité (DNI)\n\n⏱️ Délai de traitement: 7 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **DNI - National Identity Document**\n\n💰 **Costs:**\n• Expedition: 15,000 XAF\n• Renewal: 12,000 XAF\n\n📄 **Description:**\nIssuance and renewal of National Identity Document (DNI)\n\n⏱️ Processing time: 7 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"dni\",\"cedula\",\"identidad\",\"identity card\",\"carte d'identité\",\"documento identidad\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-005",
    "question_pattern": "(permiso residencia|residence permit|permis de séjour|residencia|residence)",
    "intent": "get_general_info",
    "response_es": "📋 **Permiso de Residencia**\n\n💰 **Costos:**\n• Expedición: 80,000 XAF\n\n\n📄 **Descripción:**\nSolicitud de permiso de residencia para extranjeros\n\n⏱️ Plazo de procesamiento: 30 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Permis de Séjour**\n\n💰 **Coûts:**\n• Expédition: 80,000 XAF\n\n\n📄 **Description:**\nDemande de permis de séjour pour étrangers\n\n⏱️ Délai de traitement: 30 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Residence Permit**\n\n💰 **Costs:**\n• Expedition: 80,000 XAF\n\n\n📄 **Description:**\nResidence permit application for foreigners\n\n⏱️ Processing time: 30 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"permiso residencia\",\"residence permit\",\"permis de séjour\",\"residencia\",\"residence\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-006",
    "question_pattern": "(permiso trabajo|work permit|permis de travail|trabajo|work)",
    "intent": "get_general_info",
    "response_es": "📋 **Permiso de Trabajo**\n\n💰 **Costos:**\n• Expedición: 100,000 XAF\n\n\n📄 **Descripción:**\nSolicitud de permiso de trabajo para extranjeros\n\n⏱️ Plazo de procesamiento: 30 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Permis de Travail**\n\n💰 **Coûts:**\n• Expédition: 100,000 XAF\n\n\n📄 **Description:**\nDemande de permis de travail pour étrangers\n\n⏱️ Délai de traitement: 30 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Work Permit**\n\n💰 **Costs:**\n• Expedition: 100,000 XAF\n\n\n📄 **Description:**\nWork permit application for foreigners\n\n⏱️ Processing time: 30 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"permiso trabajo\",\"work permit\",\"permis de travail\",\"trabajo\",\"work\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-007",
    "question_pattern": "(registro empresa|business registration|enregistrement entreprise|empresa|business)",
    "intent": "get_general_info",
    "response_es": "📋 **Registro de Empresa**\n\n💰 **Costos:**\n• Expedición: 150,000 XAF\n\n\n📄 **Descripción:**\nRegistro oficial de nueva empresa o negocio\n\n⏱️ Plazo de procesamiento: 45 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Enregistrement d'Entreprise**\n\n💰 **Coûts:**\n• Expédition: 150,000 XAF\n\n\n📄 **Description:**\nEnregistrement officiel d'une nouvelle entreprise\n\n⏱️ Délai de traitement: 45 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Business Registration**\n\n💰 **Costs:**\n• Expedition: 150,000 XAF\n\n\n📄 **Description:**\nOfficial registration of new business or company\n\n⏱️ Processing time: 45 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"registro empresa\",\"business registration\",\"enregistrement entreprise\",\"empresa\",\"business\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-008",
    "question_pattern": "(licencia comercial|commercial license|licence commerciale|negocio|commerce)",
    "intent": "get_general_info",
    "response_es": "📋 **Licencia Comercial**\n\n💰 **Costos:**\n• Expedición: 200,000 XAF\n• Renovación: 150,000 XAF\n\n📄 **Descripción:**\nLicencia para operación de actividad comercial\n\n⏱️ Plazo de procesamiento: 30 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Licence Commerciale**\n\n💰 **Coûts:**\n• Expédition: 200,000 XAF\n• Renouvellement: 150,000 XAF\n\n📄 **Description:**\nLicence pour l'exploitation d'une activité commerciale\n\n⏱️ Délai de traitement: 30 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Commercial License**\n\n💰 **Costs:**\n• Expedition: 200,000 XAF\n• Renewal: 150,000 XAF\n\n📄 **Description:**\nLicense for commercial activity operation\n\n⏱️ Processing time: 30 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"licencia comercial\",\"commercial license\",\"licence commerciale\",\"negocio\",\"commerce\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-009",
    "question_pattern": "(certificado nacimiento|birth certificate|acte de naissance|nacimiento|birth)",
    "intent": "get_general_info",
    "response_es": "📋 **Certificado de Nacimiento**\n\n💰 **Costos:**\n• Expedición: 5,000 XAF\n\n\n📄 **Descripción:**\nSolicitud de certificado de nacimiento\n\n⏱️ Plazo de procesamiento: 3 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Acte de Naissance**\n\n💰 **Coûts:**\n• Expédition: 5,000 XAF\n\n\n📄 **Description:**\nDemande d acte de naissance\n\n⏱️ Délai de traitement: 3 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Birth Certificate**\n\n💰 **Costs:**\n• Expedition: 5,000 XAF\n\n\n📄 **Description:**\nBirth certificate request\n\n⏱️ Processing time: 3 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"certificado nacimiento\",\"birth certificate\",\"acte de naissance\",\"nacimiento\",\"birth\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-010",
    "question_pattern": "(certificado matrimonio|marriage certificate|acte de mariage|matrimonio|marriage)",
    "intent": "get_general_info",
    "response_es": "📋 **Certificado de Matrimonio**\n\n💰 **Costos:**\n• Expedición: 5,000 XAF\n\n\n📄 **Descripción:**\nSolicitud de certificado de matrimonio\n\n⏱️ Plazo de procesamiento: 3 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Acte de Mariage**\n\n💰 **Coûts:**\n• Expédition: 5,000 XAF\n\n\n📄 **Description:**\nDemande d acte de mariage\n\n⏱️ Délai de traitement: 3 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Marriage Certificate**\n\n💰 **Costs:**\n• Expedition: 5,000 XAF\n\n\n📄 **Description:**\nMarriage certificate request\n\n⏱️ Processing time: 3 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"certificado matrimonio\",\"marriage certificate\",\"acte de mariage\",\"matrimonio\",\"marriage\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-011",
    "question_pattern": "(certificado defuncion|death certificate|acte de décès|defuncion|death)",
    "intent": "get_general_info",
    "response_es": "📋 **Certificado de Defunción**\n\n💰 **Costos:**\n• Expedición: 5,000 XAF\n\n\n📄 **Descripción:**\nSolicitud de certificado de defunción\n\n⏱️ Plazo de procesamiento: 3 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Acte de Décès**\n\n💰 **Coûts:**\n• Expédition: 5,000 XAF\n\n\n📄 **Description:**\nDemande d acte de décès\n\n⏱️ Délai de traitement: 3 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Death Certificate**\n\n💰 **Costs:**\n• Expedition: 5,000 XAF\n\n\n📄 **Description:**\nDeath certificate request\n\n⏱️ Processing time: 3 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"certificado defuncion\",\"death certificate\",\"acte de décès\",\"defuncion\",\"death\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-012",
    "question_pattern": "(antecedentes penales|criminal record|casier judiciaire|penales|police clearance)",
    "intent": "get_general_info",
    "response_es": "📋 **Certificado de Antecedentes Penales**\n\n💰 **Costos:**\n• Expedición: 10,000 XAF\n\n\n📄 **Descripción:**\nCertificado de antecedentes penales para trámites oficiales\n\n⏱️ Plazo de procesamiento: 7 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Certificat de Casier Judiciaire**\n\n💰 **Coûts:**\n• Expédition: 10,000 XAF\n\n\n📄 **Description:**\nCertificat de casier judiciaire pour démarches officielles\n\n⏱️ Délai de traitement: 7 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Criminal Record Certificate**\n\n💰 **Costs:**\n• Expedition: 10,000 XAF\n\n\n📄 **Description:**\nCriminal record certificate for official procedures\n\n⏱️ Processing time: 7 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"antecedentes penales\",\"criminal record\",\"casier judiciaire\",\"penales\",\"police clearance\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-013",
    "question_pattern": "(permiso construccion|building permit|permis de construire|construccion|building)",
    "intent": "get_general_info",
    "response_es": "📋 **Permiso de Construcción**\n\n💰 **Costos:**\n• Expedición: 120,000 XAF\n\n\n📄 **Descripción:**\nPermiso para construcción de edificaciones\n\n⏱️ Plazo de procesamiento: 60 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Permis de Construire**\n\n💰 **Coûts:**\n• Expédition: 120,000 XAF\n\n\n📄 **Description:**\nPermis pour construction de bâtiments\n\n⏱️ Délai de traitement: 60 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Building Permit**\n\n💰 **Costs:**\n• Expedition: 120,000 XAF\n\n\n📄 **Description:**\nPermit for building construction\n\n⏱️ Processing time: 60 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"permiso construccion\",\"building permit\",\"permis de construire\",\"construccion\",\"building\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-014",
    "question_pattern": "(registro propiedad|property registration|enregistrement propriété|propiedad|property)",
    "intent": "get_general_info",
    "response_es": "📋 **Registro de Propiedad**\n\n💰 **Costos:**\n• Expedición: 200,000 XAF\n\n\n📄 **Descripción:**\nRegistro oficial de propiedad inmobiliaria\n\n⏱️ Plazo de procesamiento: 45 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Enregistrement de Propriété**\n\n💰 **Coûts:**\n• Expédition: 200,000 XAF\n\n\n📄 **Description:**\nEnregistrement officiel de propriété immobilière\n\n⏱️ Délai de traitement: 45 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Property Registration**\n\n💰 **Costs:**\n• Expedition: 200,000 XAF\n\n\n📄 **Description:**\nOfficial real estate property registration\n\n⏱️ Processing time: 45 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"registro propiedad\",\"property registration\",\"enregistrement propriété\",\"propiedad\",\"property\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-015",
    "question_pattern": "(licencia profesional|professional license|licence professionnelle|medico|abogado|doctor|lawyer)",
    "intent": "get_general_info",
    "response_es": "📋 **Licencia Profesional**\n\n💰 **Costos:**\n• Expedición: 80,000 XAF\n• Renovación: 60,000 XAF\n\n📄 **Descripción:**\nLicencia para ejercicio profesional (médicos, abogados, ingenieros)\n\n⏱️ Plazo de procesamiento: 30 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Licence Professionnelle**\n\n💰 **Coûts:**\n• Expédition: 80,000 XAF\n• Renouvellement: 60,000 XAF\n\n📄 **Description:**\nLicence pour exercice professionnel (médecins, avocats, ingénieurs)\n\n⏱️ Délai de traitement: 30 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Professional License**\n\n💰 **Costs:**\n• Expedition: 80,000 XAF\n• Renewal: 60,000 XAF\n\n📄 **Description:**\nLicense for professional practice (doctors, lawyers, engineers)\n\n⏱️ Processing time: 30 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"licencia profesional\",\"professional license\",\"licence professionnelle\",\"medico\",\"abogado\",\"doctor\",\"lawyer\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-016",
    "question_pattern": "(importacion vehiculo|vehicle import|importation véhicule|vehiculo|coche|car)",
    "intent": "get_general_info",
    "response_es": "📋 **Permiso de Importación de Vehículo**\n\n💰 **Costos:**\n• Expedición: 250,000 XAF\n\n\n📄 **Descripción:**\nPermiso para importación de vehículos\n\n⏱️ Plazo de procesamiento: 20 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Permis d Importation de Véhicule**\n\n💰 **Coûts:**\n• Expédition: 250,000 XAF\n\n\n📄 **Description:**\nPermis pour importation de véhicules\n\n⏱️ Délai de traitement: 20 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Vehicle Import Permit**\n\n💰 **Costs:**\n• Expedition: 250,000 XAF\n\n\n📄 **Description:**\nPermit for vehicle importation\n\n⏱️ Processing time: 20 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"importacion vehiculo\",\"vehicle import\",\"importation véhicule\",\"vehiculo\",\"coche\",\"car\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-017",
    "question_pattern": "(matricula escolar|school enrollment|inscription scolaire|escuela|school)",
    "intent": "get_general_info",
    "response_es": "📋 **Matrícula Escolar**\n\n💰 **Costos:**\n• Expedición: 15,000 XAF\n\n\n📄 **Descripción:**\nRegistro y matrícula en instituciones educativas públicas\n\n⏱️ Plazo de procesamiento: 5 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Inscription Scolaire**\n\n💰 **Coûts:**\n• Expédition: 15,000 XAF\n\n\n📄 **Description:**\nInscription dans les établissements éducatifs publics\n\n⏱️ Délai de traitement: 5 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **School Enrollment**\n\n💰 **Costs:**\n• Expedition: 15,000 XAF\n\n\n📄 **Description:**\nRegistration in public educational institutions\n\n⏱️ Processing time: 5 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"matricula escolar\",\"school enrollment\",\"inscription scolaire\",\"escuela\",\"school\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-018",
    "question_pattern": "(registro civil|civil registry|registre civil|civil|registry)",
    "intent": "get_general_info",
    "response_es": "📋 **Registro Civil**\n\n💰 **Costos:**\n• Expedición: 8,000 XAF\n\n\n📄 **Descripción:**\nInscripción en el Registro Civil (nacimientos, matrimonios, defunciones)\n\n⏱️ Plazo de procesamiento: 5 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Registre Civil**\n\n💰 **Coûts:**\n• Expédition: 8,000 XAF\n\n\n📄 **Description:**\nInscription au Registre Civil (naissances, mariages, décès)\n\n⏱️ Délai de traitement: 5 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Civil Registry**\n\n💰 **Costs:**\n• Expedition: 8,000 XAF\n\n\n📄 **Description:**\nCivil Registry inscription (births, marriages, deaths)\n\n⏱️ Processing time: 5 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"registro civil\",\"civil registry\",\"registre civil\",\"civil\",\"registry\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-019",
    "question_pattern": "(permiso exportacion|export permit|permis d exportation|exportacion|export)",
    "intent": "get_general_info",
    "response_es": "📋 **Permiso de Exportación**\n\n💰 **Costos:**\n• Expedición: 180,000 XAF\n\n\n📄 **Descripción:**\nPermiso para exportación de mercancías\n\n⏱️ Plazo de procesamiento: 15 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Permis d'Exportation**\n\n💰 **Coûts:**\n• Expédition: 180,000 XAF\n\n\n📄 **Description:**\nPermis pour exportation de marchandises\n\n⏱️ Délai de traitement: 15 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Export Permit**\n\n💰 **Costs:**\n• Expedition: 180,000 XAF\n\n\n📄 **Description:**\nPermit for goods exportation\n\n⏱️ Processing time: 15 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"permiso exportacion\",\"export permit\",\"permis d exportation\",\"exportacion\",\"export\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-020",
    "question_pattern": "(certificado salud|health certificate|certificat de santé|salud|health)",
    "intent": "get_general_info",
    "response_es": "📋 **Certificado de Salud**\n\n💰 **Costos:**\n• Expedición: 12,000 XAF\n\n\n📄 **Descripción:**\nCertificado médico oficial para trámites\n\n⏱️ Plazo de procesamiento: 2 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Certificat de Santé**\n\n💰 **Coûts:**\n• Expédition: 12,000 XAF\n\n\n📄 **Description:**\nCertificat médical officiel pour démarches\n\n⏱️ Délai de traitement: 2 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Health Certificate**\n\n💰 **Costs:**\n• Expedition: 12,000 XAF\n\n\n📄 **Description:**\nOfficial medical certificate for procedures\n\n⏱️ Processing time: 2 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"certificado salud\",\"health certificate\",\"certificat de santé\",\"salud\",\"health\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-021",
    "question_pattern": "(patente comercial|trade patent|patente commerciale|patente|patent)",
    "intent": "get_general_info",
    "response_es": "📋 **Patente Comercial**\n\n💰 **Costos:**\n• Expedición: 90,000 XAF\n• Renovación: 90,000 XAF\n\n📄 **Descripción:**\nPatente anual para ejercicio de actividad comercial\n\n⏱️ Plazo de procesamiento: 10 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Patente Commerciale**\n\n💰 **Coûts:**\n• Expédition: 90,000 XAF\n• Renouvellement: 90,000 XAF\n\n📄 **Description:**\nPatente annuelle pour exercice d activité commerciale\n\n⏱️ Délai de traitement: 10 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Trade Patent**\n\n💰 **Costs:**\n• Expedition: 90,000 XAF\n• Renewal: 90,000 XAF\n\n📄 **Description:**\nAnnual patent for commercial activity\n\n⏱️ Processing time: 10 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"patente comercial\",\"trade patent\",\"patente commerciale\",\"patente\",\"patent\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-022",
    "question_pattern": "(registro marca|trademark registration|enregistrement marque|marca|trademark)",
    "intent": "get_general_info",
    "response_es": "📋 **Registro de Marca**\n\n💰 **Costos:**\n• Expedición: 300,000 XAF\n\n\n📄 **Descripción:**\nRegistro oficial de marca comercial\n\n⏱️ Plazo de procesamiento: 90 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Enregistrement de Marque**\n\n💰 **Coûts:**\n• Expédition: 300,000 XAF\n\n\n📄 **Description:**\nEnregistrement officiel de marque commerciale\n\n⏱️ Délai de traitement: 90 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Trademark Registration**\n\n💰 **Costs:**\n• Expedition: 300,000 XAF\n\n\n📄 **Description:**\nOfficial trademark registration\n\n⏱️ Processing time: 90 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"registro marca\",\"trademark registration\",\"enregistrement marque\",\"marca\",\"trademark\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-023",
    "question_pattern": "(permiso ambiental|environmental permit|permis environnemental|ambiental|environmental)",
    "intent": "get_general_info",
    "response_es": "📋 **Permiso Ambiental**\n\n💰 **Costos:**\n• Expedición: 250,000 XAF\n\n\n📄 **Descripción:**\nPermiso para actividades con impacto ambiental\n\n⏱️ Plazo de procesamiento: 60 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Permis Environnemental**\n\n💰 **Coûts:**\n• Expédition: 250,000 XAF\n\n\n📄 **Description:**\nPermis pour activités avec impact environnemental\n\n⏱️ Délai de traitement: 60 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Environmental Permit**\n\n💰 **Costs:**\n• Expedition: 250,000 XAF\n\n\n📄 **Description:**\nPermit for activities with environmental impact\n\n⏱️ Processing time: 60 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"permiso ambiental\",\"environmental permit\",\"permis environnemental\",\"ambiental\",\"environmental\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-024",
    "question_pattern": "(licencia sanitaria|sanitary license|licence sanitaire|sanitaria|sanitary|restaurante)",
    "intent": "get_general_info",
    "response_es": "📋 **Licencia Sanitaria**\n\n💰 **Costos:**\n• Expedición: 50,000 XAF\n• Renovación: 40,000 XAF\n\n📄 **Descripción:**\nLicencia sanitaria para establecimientos alimentarios\n\n⏱️ Plazo de procesamiento: 20 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Licence Sanitaire**\n\n💰 **Coûts:**\n• Expédition: 50,000 XAF\n• Renouvellement: 40,000 XAF\n\n📄 **Description:**\nLicence sanitaire pour établissements alimentaires\n\n⏱️ Délai de traitement: 20 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Sanitary License**\n\n💰 **Costs:**\n• Expedition: 50,000 XAF\n• Renewal: 40,000 XAF\n\n📄 **Description:**\nSanitary license for food establishments\n\n⏱️ Processing time: 20 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"licencia sanitaria\",\"sanitary license\",\"licence sanitaire\",\"sanitaria\",\"sanitary\",\"restaurante\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-025",
    "question_pattern": "(certificado origen|certificate of origin|certificat origine|origen|origin)",
    "intent": "get_general_info",
    "response_es": "📋 **Certificado de Origen**\n\n💰 **Costos:**\n• Expedición: 20,000 XAF\n\n\n📄 **Descripción:**\nCertificado de origen para exportación de productos\n\n⏱️ Plazo de procesamiento: 3 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Certificat d'Origine**\n\n💰 **Coûts:**\n• Expédition: 20,000 XAF\n\n\n📄 **Description:**\nCertificat d'origine pour exportation de produits\n\n⏱️ Délai de traitement: 3 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Certificate of Origin**\n\n💰 **Costs:**\n• Expedition: 20,000 XAF\n\n\n📄 **Description:**\nCertificate of origin for product exportation\n\n⏱️ Processing time: 3 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"certificado origen\",\"certificate of origin\",\"certificat origine\",\"origen\",\"origin\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-026",
    "question_pattern": "(permiso minero|mining permit|permis minier|mineria|mining)",
    "intent": "get_general_info",
    "response_es": "📋 **Permiso de Exploración Minera**\n\n💰 **Costos:**\n• Expedición: 500,000 XAF\n\n\n📄 **Descripción:**\nPermiso para exploración y explotación minera\n\n⏱️ Plazo de procesamiento: 120 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Permis d'Exploration Minière**\n\n💰 **Coûts:**\n• Expédition: 500,000 XAF\n\n\n📄 **Description:**\nPermis pour exploration et exploitation minière\n\n⏱️ Délai de traitement: 120 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Mining Exploration Permit**\n\n💰 **Costs:**\n• Expedition: 500,000 XAF\n\n\n📄 **Description:**\nPermit for mining exploration and exploitation\n\n⏱️ Processing time: 120 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"permiso minero\",\"mining permit\",\"permis minier\",\"mineria\",\"mining\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-027",
    "question_pattern": "(licencia turismo|tourism license|licence tourisme|turismo|tourism|hotel)",
    "intent": "get_general_info",
    "response_es": "📋 **Licencia de Turismo**\n\n💰 **Costos:**\n• Expedición: 120,000 XAF\n• Renovación: 100,000 XAF\n\n📄 **Descripción:**\nLicencia para operación de establecimientos turísticos\n\n⏱️ Plazo de procesamiento: 30 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Licence de Tourisme**\n\n💰 **Coûts:**\n• Expédition: 120,000 XAF\n• Renouvellement: 100,000 XAF\n\n📄 **Description:**\nLicence pour exploitation d établissements touristiques\n\n⏱️ Délai de traitement: 30 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Tourism License**\n\n💰 **Costs:**\n• Expedition: 120,000 XAF\n• Renewal: 100,000 XAF\n\n📄 **Description:**\nLicense for tourism establishment operation\n\n⏱️ Processing time: 30 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"licencia turismo\",\"tourism license\",\"licence tourisme\",\"turismo\",\"tourism\",\"hotel\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-028",
    "question_pattern": "(certificado residencia|residence certificate|certificat de résidence|residencia fiscal|tax residence)",
    "intent": "get_general_info",
    "response_es": "📋 **Certificado de Residencia Fiscal**\n\n💰 **Costos:**\n• Expedición: 15,000 XAF\n\n\n📄 **Descripción:**\nCertificado de residencia fiscal para trámites internacionales\n\n⏱️ Plazo de procesamiento: 10 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Certificat de Résidence Fiscale**\n\n💰 **Coûts:**\n• Expédition: 15,000 XAF\n\n\n📄 **Description:**\nCertificat de résidence fiscale pour démarches internationales\n\n⏱️ Délai de traitement: 10 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Tax Residence Certificate**\n\n💰 **Costs:**\n• Expedition: 15,000 XAF\n\n\n📄 **Description:**\nTax residence certificate for international procedures\n\n⏱️ Processing time: 10 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"certificado residencia\",\"residence certificate\",\"certificat de résidence\",\"residencia fiscal\",\"tax residence\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-029",
    "question_pattern": "(permiso forestal|forestry permit|permis forestier|forestal|forestry|tala|madera)",
    "intent": "get_general_info",
    "response_es": "📋 **Permiso Forestal**\n\n💰 **Costos:**\n• Expedición: 180,000 XAF\n\n\n📄 **Descripción:**\nPermiso para explotación forestal y tala de árboles\n\n⏱️ Plazo de procesamiento: 45 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Permis Forestier**\n\n💰 **Coûts:**\n• Expédition: 180,000 XAF\n\n\n📄 **Description:**\nPermis pour exploitation forestière et coupe d'arbres\n\n⏱️ Délai de traitement: 45 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Forestry Permit**\n\n💰 **Costs:**\n• Expedition: 180,000 XAF\n\n\n📄 **Description:**\nPermit for forestry exploitation and tree cutting\n\n⏱️ Processing time: 45 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"permiso forestal\",\"forestry permit\",\"permis forestier\",\"forestal\",\"forestry\",\"tala\",\"madera\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-service-030",
    "question_pattern": "(registro laboral|labor registration|enregistrement travail|laboral|labor|empleados)",
    "intent": "get_general_info",
    "response_es": "📋 **Registro de Trabajadores**\n\n💰 **Costos:**\n• Expedición: 10,000 XAF\n\n\n📄 **Descripción:**\nRegistro de empleados en sistema de seguridad social\n\n⏱️ Plazo de procesamiento: 7 días\n\n💡 Usa la búsqueda para encontrar este servicio y ver más detalles.",
    "response_fr": "📋 **Enregistrement de Travailleurs**\n\n💰 **Coûts:**\n• Expédition: 10,000 XAF\n\n\n📄 **Description:**\nEnregistrement des employés au système de sécurité sociale\n\n⏱️ Délai de traitement: 7 jours\n\n💡 Utilisez la recherche pour trouver ce service et voir plus de détails.",
    "response_en": "📋 **Workers Registration**\n\n💰 **Costs:**\n• Expedition: 10,000 XAF\n\n\n📄 **Description:**\nEmployee registration in social security system\n\n⏱️ Processing time: 7 days\n\n💡 Use search to find this service and see more details.",
    "follow_up_suggestions": "[\"Ver documentos requeridos\",\"Ver procedimientos\",\"Buscar servicios\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"registro laboral\",\"labor registration\",\"enregistrement travail\",\"laboral\",\"labor\",\"empleados\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-category-001",
    "question_pattern": "(impuestos|taxes|impôts|fiscal|tax)",
    "intent": "search_service",
    "response_es": "📂 **Categoría: Impuestos**\n\nServicios relacionados con impuestos y tributos fiscales\n\n💡 Usa la búsqueda para explorar servicios específicos en esta categoría.\n\n📊 Contamos con múltiples servicios disponibles.",
    "response_fr": "📂 **Catégorie: Impôts**\n\nServices liés aux impôts et taxes fiscales\n\n💡 Utilisez la recherche pour explorer les services spécifiques de cette catégorie.\n\n📊 Nous avons plusieurs services disponibles.",
    "response_en": "📂 **Category: Taxes**\n\nServices related to taxes and fiscal duties\n\n💡 Use search to explore specific services in this category.\n\n📊 We have multiple services available.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"¿Qué documentos necesito?\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"impuestos\",\"taxes\",\"impôts\",\"fiscal\",\"tax\"]",
    "priority": 7,
    "is_active": 1
  },
  {
    "id": "faq-category-002",
    "question_pattern": "(documentos personales|personal documents|documents personnels|certificados|certificates)",
    "intent": "search_service",
    "response_es": "📂 **Categoría: Documentos Personales**\n\nCertificados, actas y documentos de identidad\n\n💡 Usa la búsqueda para explorar servicios específicos en esta categoría.\n\n📊 Contamos con múltiples servicios disponibles.",
    "response_fr": "📂 **Catégorie: Documents Personnels**\n\nCertificats, actes et documents d'identité\n\n💡 Utilisez la recherche pour explorer les services spécifiques de cette catégorie.\n\n📊 Nous avons plusieurs services disponibles.",
    "response_en": "📂 **Category: Personal Documents**\n\nCertificates, records and identity documents\n\n💡 Use search to explore specific services in this category.\n\n📊 We have multiple services available.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"¿Qué documentos necesito?\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"documentos personales\",\"personal documents\",\"documents personnels\",\"certificados\",\"certificates\"]",
    "priority": 7,
    "is_active": 1
  },
  {
    "id": "faq-category-003",
    "question_pattern": "(permisos|permits|permis|licencias|licenses)",
    "intent": "search_service",
    "response_es": "📂 **Categoría: Permisos y Licencias**\n\nPermisos de trabajo, residencia, conducir y comerciales\n\n💡 Usa la búsqueda para explorar servicios específicos en esta categoría.\n\n📊 Contamos con múltiples servicios disponibles.",
    "response_fr": "📂 **Catégorie: Permis et Licences**\n\nPermis de travail, séjour, conduire et commerciaux\n\n💡 Utilisez la recherche pour explorer les services spécifiques de cette catégorie.\n\n📊 Nous avons plusieurs services disponibles.",
    "response_en": "📂 **Category: Permits and Licenses**\n\nWork, residence, driving and commercial permits\n\n💡 Use search to explore specific services in this category.\n\n📊 We have multiple services available.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"¿Qué documentos necesito?\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"permisos\",\"permits\",\"permis\",\"licencias\",\"licenses\"]",
    "priority": 7,
    "is_active": 1
  },
  {
    "id": "faq-category-004",
    "question_pattern": "(empresas|business|entreprises|comercio|commerce)",
    "intent": "search_service",
    "response_es": "📂 **Categoría: Servicios Empresariales**\n\nRegistro, licencias y trámites para empresas\n\n💡 Usa la búsqueda para explorar servicios específicos en esta categoría.\n\n📊 Contamos con múltiples servicios disponibles.",
    "response_fr": "📂 **Catégorie: Services aux Entreprises**\n\nEnregistrement, licences et démarches pour entreprises\n\n💡 Utilisez la recherche pour explorer les services spécifiques de cette catégorie.\n\n📊 Nous avons plusieurs services disponibles.",
    "response_en": "📂 **Category: Business Services**\n\nRegistration, licenses and procedures for businesses\n\n💡 Use search to explore specific services in this category.\n\n📊 We have multiple services available.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"¿Qué documentos necesito?\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"empresas\",\"business\",\"entreprises\",\"comercio\",\"commerce\"]",
    "priority": 7,
    "is_active": 1
  },
  {
    "id": "faq-category-005",
    "question_pattern": "(aduanas|customs|douanes|importacion|exportacion|import|export)",
    "intent": "search_service",
    "response_es": "📂 **Categoría: Aduanas**\n\nTrámites de importación, exportación y aranceles\n\n💡 Usa la búsqueda para explorar servicios específicos en esta categoría.\n\n📊 Contamos con múltiples servicios disponibles.",
    "response_fr": "📂 **Catégorie: Douanes**\n\nDémarches d'importation, exportation et tarifs douaniers\n\n💡 Utilisez la recherche pour explorer les services spécifiques de cette catégorie.\n\n📊 Nous avons plusieurs services disponibles.",
    "response_en": "📂 **Category: Customs**\n\nImport, export and customs duties procedures\n\n💡 Use search to explore specific services in this category.\n\n📊 We have multiple services available.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"¿Qué documentos necesito?\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"aduanas\",\"customs\",\"douanes\",\"importacion\",\"exportacion\",\"import\",\"export\"]",
    "priority": 7,
    "is_active": 1
  },
  {
    "id": "faq-category-006",
    "question_pattern": "(salud|health|santé|medico|hospital|medical)",
    "intent": "search_service",
    "response_es": "📂 **Categoría: Servicios de Salud**\n\nCertificados médicos, licencias sanitarias y servicios de salud\n\n💡 Usa la búsqueda para explorar servicios específicos en esta categoría.\n\n📊 Contamos con múltiples servicios disponibles.",
    "response_fr": "📂 **Catégorie: Services de Santé**\n\nCertificats médicaux, licences sanitaires et services de santé\n\n💡 Utilisez la recherche pour explorer les services spécifiques de cette catégorie.\n\n📊 Nous avons plusieurs services disponibles.",
    "response_en": "📂 **Category: Health Services**\n\nMedical certificates, sanitary licenses and health services\n\n💡 Use search to explore specific services in this category.\n\n📊 We have multiple services available.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"¿Qué documentos necesito?\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"salud\",\"health\",\"santé\",\"medico\",\"hospital\",\"medical\"]",
    "priority": 7,
    "is_active": 1
  },
  {
    "id": "faq-category-007",
    "question_pattern": "(educacion|education|éducation|escuela|universidad|school|university)",
    "intent": "search_service",
    "response_es": "📂 **Categoría: Educación**\n\nMatrícula escolar, certificados educativos y servicios académicos\n\n💡 Usa la búsqueda para explorar servicios específicos en esta categoría.\n\n📊 Contamos con múltiples servicios disponibles.",
    "response_fr": "📂 **Catégorie: Éducation**\n\nInscription scolaire, certificats éducatifs et services académiques\n\n💡 Utilisez la recherche pour explorer les services spécifiques de cette catégorie.\n\n📊 Nous avons plusieurs services disponibles.",
    "response_en": "📂 **Category: Education**\n\nSchool enrollment, educational certificates and academic services\n\n💡 Use search to explore specific services in this category.\n\n📊 We have multiple services available.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"¿Qué documentos necesito?\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"educacion\",\"education\",\"éducation\",\"escuela\",\"universidad\",\"school\",\"university\"]",
    "priority": 7,
    "is_active": 1
  },
  {
    "id": "faq-category-008",
    "question_pattern": "(propiedad|property|propriété|inmueble|terreno|real estate)",
    "intent": "search_service",
    "response_es": "📂 **Categoría: Propiedad e Inmuebles**\n\nRegistro de propiedad, permisos de construcción y trámites inmobiliarios\n\n💡 Usa la búsqueda para explorar servicios específicos en esta categoría.\n\n📊 Contamos con múltiples servicios disponibles.",
    "response_fr": "📂 **Catégorie: Propriété et Immobilier**\n\nEnregistrement de propriété, permis de construire et démarches immobilières\n\n💡 Utilisez la recherche pour explorer les services spécifiques de cette catégorie.\n\n📊 Nous avons plusieurs services disponibles.",
    "response_en": "📂 **Category: Property and Real Estate**\n\nProperty registration, building permits and real estate procedures\n\n💡 Use search to explore specific services in this category.\n\n📊 We have multiple services available.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"¿Qué documentos necesito?\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"propiedad\",\"property\",\"propriété\",\"inmueble\",\"terreno\",\"real estate\"]",
    "priority": 7,
    "is_active": 1
  },
  {
    "id": "faq-category-009",
    "question_pattern": "(trabajo|labor|travail|empleo|employment|emploi)",
    "intent": "search_service",
    "response_es": "📂 **Categoría: Trabajo y Empleo**\n\nRegistro laboral, permisos de trabajo y servicios de empleo\n\n💡 Usa la búsqueda para explorar servicios específicos en esta categoría.\n\n📊 Contamos con múltiples servicios disponibles.",
    "response_fr": "📂 **Catégorie: Travail et Emploi**\n\nEnregistrement au travail, permis de travail et services d emploi\n\n💡 Utilisez la recherche pour explorer les services spécifiques de cette catégorie.\n\n📊 Nous avons plusieurs services disponibles.",
    "response_en": "📂 **Category: Labor and Employment**\n\nLabor registration, work permits and employment services\n\n💡 Use search to explore specific services in this category.\n\n📊 We have multiple services available.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"¿Qué documentos necesito?\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"trabajo\",\"labor\",\"travail\",\"empleo\",\"employment\",\"emploi\"]",
    "priority": 7,
    "is_active": 1
  },
  {
    "id": "faq-category-010",
    "question_pattern": "(medio ambiente|environment|environnement|ecologia|ecology)",
    "intent": "search_service",
    "response_es": "📂 **Categoría: Medio Ambiente**\n\nPermisos ambientales y trámites ecológicos\n\n💡 Usa la búsqueda para explorar servicios específicos en esta categoría.\n\n📊 Contamos con múltiples servicios disponibles.",
    "response_fr": "📂 **Catégorie: Environnement**\n\nPermis environnementaux et démarches écologiques\n\n💡 Utilisez la recherche pour explorer les services spécifiques de cette catégorie.\n\n📊 Nous avons plusieurs services disponibles.",
    "response_en": "📂 **Category: Environment**\n\nEnvironmental permits and ecological procedures\n\n💡 Use search to explore specific services in this category.\n\n📊 We have multiple services available.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"¿Qué documentos necesito?\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"medio ambiente\",\"environment\",\"environnement\",\"ecologia\",\"ecology\"]",
    "priority": 7,
    "is_active": 1
  },
  {
    "id": "faq-category-011",
    "question_pattern": "(transporte|transportation|transport|vehiculo|vehicle)",
    "intent": "search_service",
    "response_es": "📂 **Categoría: Transportes**\n\nLicencias de conducir, importación de vehículos y servicios de transporte\n\n💡 Usa la búsqueda para explorar servicios específicos en esta categoría.\n\n📊 Contamos con múltiples servicios disponibles.",
    "response_fr": "📂 **Catégorie: Transports**\n\nPermis de conduire, importation de véhicules et services de transport\n\n💡 Utilisez la recherche pour explorer les services spécifiques de cette catégorie.\n\n📊 Nous avons plusieurs services disponibles.",
    "response_en": "📂 **Category: Transportation**\n\nDriver's licenses, vehicle import and transportation services\n\n💡 Use search to explore specific services in this category.\n\n📊 We have multiple services available.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"¿Qué documentos necesito?\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"transporte\",\"transportation\",\"transport\",\"vehiculo\",\"vehicle\"]",
    "priority": 7,
    "is_active": 1
  },
  {
    "id": "faq-category-012",
    "question_pattern": "(turismo|tourism|tourisme|hotel|hosteleria)",
    "intent": "search_service",
    "response_es": "📂 **Categoría: Turismo y Hostelería**\n\nLicencias turísticas y servicios para establecimientos hoteleros\n\n💡 Usa la búsqueda para explorar servicios específicos en esta categoría.\n\n📊 Contamos con múltiples servicios disponibles.",
    "response_fr": "📂 **Catégorie: Tourisme et Hôtellerie**\n\nLicences touristiques et services pour établissements hôteliers\n\n💡 Utilisez la recherche pour explorer les services spécifiques de cette catégorie.\n\n📊 Nous avons plusieurs services disponibles.",
    "response_en": "📂 **Category: Tourism and Hospitality**\n\nTourism licenses and services for hotel establishments\n\n💡 Use search to explore specific services in this category.\n\n📊 We have multiple services available.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"¿Qué documentos necesito?\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"turismo\",\"tourism\",\"tourisme\",\"hotel\",\"hosteleria\"]",
    "priority": 7,
    "is_active": 1
  },
  {
    "id": "faq-category-013",
    "question_pattern": "(mineria|mining|mines|extractivo|extractive)",
    "intent": "search_service",
    "response_es": "📂 **Categoría: Minería y Recursos**\n\nPermisos mineros y explotación de recursos naturales\n\n💡 Usa la búsqueda para explorar servicios específicos en esta categoría.\n\n📊 Contamos con múltiples servicios disponibles.",
    "response_fr": "📂 **Catégorie: Mines et Ressources**\n\nPermis miniers et exploitation de ressources naturelles\n\n💡 Utilisez la recherche pour explorer les services spécifiques de cette catégorie.\n\n📊 Nous avons plusieurs services disponibles.",
    "response_en": "📂 **Category: Mining and Resources**\n\nMining permits and natural resources exploitation\n\n💡 Use search to explore specific services in this category.\n\n📊 We have multiple services available.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"¿Qué documentos necesito?\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"mineria\",\"mining\",\"mines\",\"extractivo\",\"extractive\"]",
    "priority": 7,
    "is_active": 1
  },
  {
    "id": "faq-category-014",
    "question_pattern": "(agricultura|agriculture|agricola|farming|agricole)",
    "intent": "search_service",
    "response_es": "📂 **Categoría: Agricultura**\n\nServicios agrícolas, permisos forestales y producción agropecuaria\n\n💡 Usa la búsqueda para explorar servicios específicos en esta categoría.\n\n📊 Contamos con múltiples servicios disponibles.",
    "response_fr": "📂 **Catégorie: Agriculture**\n\nServices agricoles, permis forestiers et production agro-pastorale\n\n💡 Utilisez la recherche pour explorer les services spécifiques de cette catégorie.\n\n📊 Nous avons plusieurs services disponibles.",
    "response_en": "📂 **Category: Agriculture**\n\nAgricultural services, forestry permits and farming production\n\n💡 Use search to explore specific services in this category.\n\n📊 We have multiple services available.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"¿Qué documentos necesito?\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"agricultura\",\"agriculture\",\"agricola\",\"farming\",\"agricole\"]",
    "priority": 7,
    "is_active": 1
  },
  {
    "id": "faq-category-015",
    "question_pattern": "(justicia|justice|judicial|legal|tribunal)",
    "intent": "search_service",
    "response_es": "📂 **Categoría: Justicia**\n\nCertificados judiciales, antecedentes penales y servicios legales\n\n💡 Usa la búsqueda para explorar servicios específicos en esta categoría.\n\n📊 Contamos con múltiples servicios disponibles.",
    "response_fr": "📂 **Catégorie: Justice**\n\nCertificats judiciaires, casier judiciaire et services légaux\n\n💡 Utilisez la recherche pour explorer les services spécifiques de cette catégorie.\n\n📊 Nous avons plusieurs services disponibles.",
    "response_en": "📂 **Category: Justice**\n\nJudicial certificates, criminal records and legal services\n\n💡 Use search to explore specific services in this category.\n\n📊 We have multiple services available.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"¿Qué documentos necesito?\"]",
    "actions": "{\"type\":\"navigate\",\"screen\":\"Search\"}",
    "keywords": "[\"justicia\",\"justice\",\"judicial\",\"legal\",\"tribunal\"]",
    "priority": 7,
    "is_active": 1
  },
  {
    "id": "faq-proc-payment",
    "question_pattern": "(pagar|payment|paiement|como pago|how to pay|comment payer|metodo pago|payment method)",
    "intent": "get_general_info",
    "response_es": "💳 **Métodos de Pago**\n\nPuedes pagar tus servicios fiscales de las siguientes formas:\n\n1️⃣ **Bancos autorizados** (efectivo o transferencia)\n2️⃣ **Oficinas gubernamentales** (pago directo)\n3️⃣ **Pago en línea** (disponible próximamente)\n\n💡 Cada servicio muestra los métodos disponibles en su ficha.",
    "response_fr": "💳 **Méthodes de Paiement**\n\nVous pouvez payer vos services fiscaux des manières suivantes:\n\n1️⃣ **Banques autorisées** (espèces ou virement)\n2️⃣ **Bureaux gouvernementaux** (paiement direct)\n3️⃣ **Paiement en ligne** (disponible prochainement)\n\n💡 Chaque service affiche les méthodes disponibles sur sa fiche.",
    "response_en": "💳 **Payment Methods**\n\nYou can pay for your fiscal services in the following ways:\n\n1️⃣ **Authorized banks** (cash or transfer)\n2️⃣ **Government offices** (direct payment)\n3️⃣ **Online payment** (coming soon)\n\n💡 Each service shows available methods on its details page.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"Usar calculadora\"]",
    "actions": null,
    "keywords": "[\"get_general_info\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-proc-appointment",
    "question_pattern": "(cita|appointment|rendez-vous|agendar|schedule|prendre rendez-vous|horario|hours|heures)",
    "intent": "get_general_info",
    "response_es": "📅 **Citas y Horarios**\n\nPara tramitar servicios fiscales:\n\n• Algunos servicios requieren cita previa\n• Otros son por orden de llegada\n• **Horario general:** Lunes a Viernes, 8:00 - 16:00\n\n💡 Consulta la ficha de cada servicio para ver si requiere cita.",
    "response_fr": "📅 **Rendez-vous et Horaires**\n\nPour traiter les services fiscaux:\n\n• Certains services nécessitent un rendez-vous\n• D'autres sont par ordre d'arrivée\n• **Horaire général:** Lundi au Vendredi, 8h00 - 16h00\n\n💡 Consultez la fiche de chaque service pour voir s'il nécessite un rendez-vous.",
    "response_en": "📅 **Appointments and Schedules**\n\nTo process fiscal services:\n\n• Some services require appointment\n• Others are first-come-first-served\n• **General hours:** Monday to Friday, 8:00 AM - 4:00 PM\n\n💡 Check each service details to see if appointment is required.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"Usar calculadora\"]",
    "actions": null,
    "keywords": "[\"get_general_info\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-proc-location",
    "question_pattern": "(oficina|office|bureau|ubicacion|location|emplacement|donde|where|ou|direccion|address|adresse)",
    "intent": "get_general_info",
    "response_es": "📍 **Ubicación de Oficinas**\n\nLas oficinas gubernamentales para servicios fiscales se encuentran en:\n\n🏛️ **Malabo** - Ministerios centrales y oficinas principales\n🏛️ **Bata** - Oficinas regionales\n\n💡 Cada servicio indica la dirección específica en su ficha.",
    "response_fr": "📍 **Emplacement des Bureaux**\n\nLes bureaux gouvernementaux pour les services fiscaux se trouvent à:\n\n🏛️ **Malabo** - Ministères centraux et bureaux principaux\n🏛️ **Bata** - Bureaux régionaux\n\n💡 Chaque service indique l'adresse spécifique sur sa fiche.",
    "response_en": "📍 **Office Locations**\n\nGovernment offices for fiscal services are located in:\n\n🏛️ **Malabo** - Central ministries and main offices\n🏛️ **Bata** - Regional offices\n\n💡 Each service shows specific address on its details page.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"Usar calculadora\"]",
    "actions": null,
    "keywords": "[\"get_general_info\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-proc-urgente",
    "question_pattern": "(urgente|urgent|express|rapido|quick|rapide|emergency|emergencia|urgence)",
    "intent": "get_general_info",
    "response_es": "⚡ **Servicios Urgentes**\n\nAlgunos servicios ofrecen tramitación urgente/express:\n\n💰 **Costo adicional:** Generalmente +50% del precio normal\n⏱️ **Plazo reducido:** 50% menos tiempo de procesamiento\n\n💡 Consulta la ficha de cada servicio para ver si ofrece modalidad urgente.",
    "response_fr": "⚡ **Services Urgents**\n\nCertains services offrent un traitement urgent/express:\n\n💰 **Coût supplémentaire:** Généralement +50% du prix normal\n⏱️ **Délai réduit:** 50% moins de temps de traitement\n\n💡 Consultez la fiche de chaque service pour voir s'il offre une modalité urgente.",
    "response_en": "⚡ **Urgent Services**\n\nSome services offer urgent/express processing:\n\n💰 **Additional cost:** Generally +50% of normal price\n⏱️ **Reduced time:** 50% less processing time\n\n💡 Check each service details to see if urgent option is available.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"Usar calculadora\"]",
    "actions": null,
    "keywords": "[\"get_general_info\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-proc-tracking",
    "question_pattern": "(seguimiento|tracking|suivi|estado|status|statut|tramite|procedure|demarche|verificar|check|verifier)",
    "intent": "get_general_info",
    "response_es": "🔍 **Seguimiento de Trámites**\n\nPara verificar el estado de tu trámite:\n\n1️⃣ **Número de expediente:** Guarda el número que te dieron al presentar\n2️⃣ **Contacto:** Llama a la oficina correspondiente\n3️⃣ **Visita presencial:** Acude con tu recibo de pago\n\n💡 El tiempo de procesamiento varía según el servicio (consulta la ficha).",
    "response_fr": "🔍 **Suivi des Démarches**\n\nPour vérifier l'état de votre démarche:\n\n1️⃣ **Numéro de dossier:** Conservez le numéro reçu lors du dépôt\n2️⃣ **Contact:** Appelez le bureau concerné\n3️⃣ **Visite en personne:** Présentez-vous avec votre reçu de paiement\n\n💡 Le délai de traitement varie selon le service (consultez la fiche).",
    "response_en": "🔍 **Procedure Tracking**\n\nTo check your procedure status:\n\n1️⃣ **File number:** Keep the number given when submitting\n2️⃣ **Contact:** Call the corresponding office\n3️⃣ **In-person visit:** Go with your payment receipt\n\n💡 Processing time varies by service (check details page).",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"Usar calculadora\"]",
    "actions": null,
    "keywords": "[\"get_general_info\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-proc-validity",
    "question_pattern": "(validez|validity|validité|vigencia|duration|durée|cuanto tiempo vale|how long valid|combien de temps valable)",
    "intent": "get_general_info",
    "response_es": "📅 **Validez de Documentos**\n\nLa vigencia de los documentos varía:\n\n📋 **Documentos de Identidad:**\n• DNI: 10 años\n• Pasaporte: 5 años\n• Licencia de conducir: 5 años\n\n📋 **Licencias Comerciales:**\n• Licencia comercial: 1 año (renovación anual)\n• Patente comercial: 1 año\n• Permiso sanitario: 1 año\n\n💡 Consulta la ficha de cada servicio para detalles específicos.",
    "response_fr": "📅 **Validité des Documents**\n\nLa durée de validité des documents varie:\n\n📋 **Documents d'Identité:**\n• DNI: 10 ans\n• Passeport: 5 ans\n• Permis de conduire: 5 ans\n\n📋 **Licences Commerciales:**\n• Licence commerciale: 1 an (renouvellement annuel)\n• Patente commerciale: 1 an\n• Permis sanitaire: 1 an\n\n💡 Consultez la fiche de chaque service pour les détails spécifiques.",
    "response_en": "📅 **Document Validity**\n\nDocument validity varies:\n\n📋 **Identity Documents:**\n• DNI: 10 years\n• Passport: 5 years\n• Driver's license: 5 years\n\n📋 **Commercial Licenses:**\n• Commercial license: 1 year (annual renewal)\n• Trade patent: 1 year\n• Sanitary permit: 1 year\n\n💡 Check each service details for specific information.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"Usar calculadora\"]",
    "actions": null,
    "keywords": "[\"get_general_info\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-proc-costs",
    "question_pattern": "(cuanto cuesta|how much|combien coute|precio|price|prix|costo|cost|coût|tarifa|fee|tarif)",
    "intent": "get_price",
    "response_es": "💰 **Costos de Servicios**\n\nLos costos varían según el servicio:\n\n**Documentos personales:** 5,000 - 50,000 XAF\n**Licencias profesionales:** 25,000 - 100,000 XAF\n**Permisos empresariales:** 80,000 - 500,000 XAF\n**Servicios aduaneros:** Variable según mercancía\n\n💡 Cada servicio muestra el costo exacto en su ficha.\n🔍 Usa la búsqueda para encontrar el servicio específico.",
    "response_fr": "💰 **Coûts des Services**\n\nLes coûts varient selon le service:\n\n**Documents personnels:** 5 000 - 50 000 XAF\n**Licences professionnelles:** 25 000 - 100 000 XAF\n**Permis d'entreprise:** 80 000 - 500 000 XAF\n**Services douaniers:** Variable selon marchandise\n\n💡 Chaque service affiche le coût exact sur sa fiche.\n🔍 Utilisez la recherche pour trouver le service spécifique.",
    "response_en": "💰 **Service Costs**\n\nCosts vary by service:\n\n**Personal documents:** 5,000 - 50,000 XAF\n**Professional licenses:** 25,000 - 100,000 XAF\n**Business permits:** 80,000 - 500,000 XAF\n**Customs services:** Variable by goods\n\n💡 Each service shows exact cost on its details page.\n🔍 Use search to find the specific service.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"Usar calculadora\"]",
    "actions": null,
    "keywords": "[\"get_price\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-proc-requirements",
    "question_pattern": "(que documentos necesito|what documents|quels documents|requisitos|requirements|exigences|que necesito|what do i need|de quoi j ai besoin)",
    "intent": "get_documents",
    "response_es": "📄 **Requisitos Documentales**\n\nLos documentos requeridos varían según el servicio:\n\n**Documentos comunes:**\n• DNI o pasaporte válido\n• Fotografías recientes\n• Comprobante de domicilio\n• Comprobante de pago\n\n💡 Cada servicio lista los documentos específicos en su ficha.\n🔍 Busca el servicio para ver la lista completa.",
    "response_fr": "📄 **Exigences Documentaires**\n\nLes documents requis varient selon le service:\n\n**Documents courants:**\n• DNI ou passeport valide\n• Photos récentes\n• Justificatif de domicile\n• Justificatif de paiement\n\n💡 Chaque service liste les documents spécifiques sur sa fiche.\n🔍 Recherchez le service pour voir la liste complète.",
    "response_en": "📄 **Documentary Requirements**\n\nRequired documents vary by service:\n\n**Common documents:**\n• Valid DNI or passport\n• Recent photographs\n• Proof of address\n• Payment receipt\n\n💡 Each service lists specific documents on its details page.\n🔍 Search for the service to see complete list.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"Usar calculadora\"]",
    "actions": null,
    "keywords": "[\"get_documents\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-proc-office-hours",
    "question_pattern": "(horario|schedule|horaire|cuando abren|when open|quand ouvert|hora atencion|office hours|heures ouverture)",
    "intent": "get_general_info",
    "response_es": "🕐 **Horarios de Atención**\n\n**Horario general:**\n📅 Lunes a Viernes: 8:00 - 16:00\n📅 Sábado y Domingo: Cerrado\n\n**Días festivos:** Cerrado\n\n⚠️ Algunos servicios tienen horarios especiales\n⏰ Se recomienda llegar temprano (antes de las 14:00)\n\n💡 Verifica en la ficha del servicio si hay horarios especiales.",
    "response_fr": "🕐 **Heures d'Ouverture**\n\n**Horaire général:**\n📅 Lundi au Vendredi: 8h00 - 16h00\n📅 Samedi et Dimanche: Fermé\n\n**Jours fériés:** Fermé\n\n⚠️ Certains services ont des horaires spéciaux\n⏰ Recommandé d'arriver tôt (avant 14h00)\n\n💡 Vérifiez sur la fiche du service s'il y a des horaires spéciaux.",
    "response_en": "🕐 **Office Hours**\n\n**General schedule:**\n📅 Monday to Friday: 8:00 AM - 4:00 PM\n📅 Saturday and Sunday: Closed\n\n**Public holidays:** Closed\n\n⚠️ Some services have special hours\n⏰ Recommended to arrive early (before 2:00 PM)\n\n💡 Check service details for special hours.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"Usar calculadora\"]",
    "actions": null,
    "keywords": "[\"get_general_info\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-proc-complaints",
    "question_pattern": "(queja|complaint|plainte|reclamacion|claim|réclamation|problema|problem|problème)",
    "intent": "get_general_info",
    "response_es": "📞 **Quejas y Reclamaciones**\n\nSi tienes un problema con tu trámite:\n\n1️⃣ **Libro de reclamaciones:** Disponible en todas las oficinas\n2️⃣ **Contacto telefónico:** Llama a la oficina correspondiente\n3️⃣ **Email institucional:** Envía tu reclamación por escrito\n4️⃣ **Atención presencial:** Solicita hablar con un supervisor\n\n⏱️ **Plazo de respuesta:** 15 días hábiles\n\n💡 Guarda siempre tu número de expediente y recibos.",
    "response_fr": "📞 **Plaintes et Réclamations**\n\nSi vous avez un problème avec votre démarche:\n\n1️⃣ **Livre de réclamations:** Disponible dans tous les bureaux\n2️⃣ **Contact téléphonique:** Appelez le bureau concerné\n3️⃣ **Email institutionnel:** Envoyez votre réclamation par écrit\n4️⃣ **Assistance en personne:** Demandez à parler à un superviseur\n\n⏱️ **Délai de réponse:** 15 jours ouvrables\n\n💡 Conservez toujours votre numéro de dossier et reçus.",
    "response_en": "📞 **Complaints and Claims**\n\nIf you have a problem with your procedure:\n\n1️⃣ **Complaint book:** Available at all offices\n2️⃣ **Phone contact:** Call the corresponding office\n3️⃣ **Institutional email:** Send your complaint in writing\n4️⃣ **In-person assistance:** Request to speak with supervisor\n\n⏱️ **Response time:** 15 business days\n\n💡 Always keep your file number and receipts.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"Usar calculadora\"]",
    "actions": null,
    "keywords": "[\"get_general_info\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-proc-online",
    "question_pattern": "(online|en linea|en ligne|internet|digital|web|portal)",
    "intent": "get_general_info",
    "response_es": "💻 **Servicios en Línea**\n\n**Actualmente disponible:**\n✅ Consulta de información de servicios (esta app)\n✅ Cálculo de tasas fiscales\n✅ Lista de documentos requeridos\n\n**Próximamente:**\n🚧 Pago en línea de servicios\n🚧 Seguimiento de trámites online\n🚧 Citas previas por internet\n\n💡 Mantente actualizado revisando esta aplicación regularmente.",
    "response_fr": "💻 **Services en Ligne**\n\n**Actuellement disponible:**\n✅ Consultation d'informations sur les services (cette app)\n✅ Calcul des taxes fiscales\n✅ Liste des documents requis\n\n**Prochainement:**\n🚧 Paiement en ligne des services\n🚧 Suivi des démarches en ligne\n🚧 Rendez-vous préalables par internet\n\n💡 Restez à jour en consultant cette application régulièrement.",
    "response_en": "💻 **Online Services**\n\n**Currently available:**\n✅ Service information consultation (this app)\n✅ Fiscal fee calculation\n✅ Required documents list\n\n**Coming soon:**\n🚧 Online payment for services\n🚧 Online procedure tracking\n🚧 Internet appointment scheduling\n\n💡 Stay updated by checking this app regularly.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"Usar calculadora\"]",
    "actions": null,
    "keywords": "[\"get_general_info\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-proc-corrections",
    "question_pattern": "(correccion|correction|error|mistake|erreur|cambio|change|changement|modificar|modify|modifier)",
    "intent": "get_general_info",
    "response_es": "✏️ **Corrección de Errores**\n\nSi tu documento tiene errores:\n\n1️⃣ **Errores menores:** Solicita corrección gratuita dentro de 30 días\n2️⃣ **Errores de oficina:** Corrección sin costo adicional\n3️⃣ **Cambios personales:** Puede requerir nuevo trámite\n\n📋 **Documentos necesarios:**\n• Documento con error\n• Prueba del error (certificado original, etc.)\n• Solicitud escrita\n\n💡 Acude a la oficina emisora con la documentación.",
    "response_fr": "✏️ **Correction d'Erreurs**\n\nSi votre document contient des erreurs:\n\n1️⃣ **Erreurs mineures:** Demande de correction gratuite dans les 30 jours\n2️⃣ **Erreurs du bureau:** Correction sans frais supplémentaires\n3️⃣ **Changements personnels:** Peut nécessiter une nouvelle démarche\n\n📋 **Documents nécessaires:**\n• Document avec erreur\n• Preuve de l'erreur (certificat original, etc.)\n• Demande écrite\n\n💡 Rendez-vous au bureau émetteur avec la documentation.",
    "response_en": "✏️ **Error Correction**\n\nIf your document has errors:\n\n1️⃣ **Minor errors:** Request free correction within 30 days\n2️⃣ **Office errors:** Correction at no additional cost\n3️⃣ **Personal changes:** May require new procedure\n\n📋 **Required documents:**\n• Document with error\n• Proof of error (original certificate, etc.)\n• Written request\n\n💡 Go to issuing office with documentation.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"Usar calculadora\"]",
    "actions": null,
    "keywords": "[\"get_general_info\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-proc-appeals",
    "question_pattern": "(apelacion|appeal|appel|recurso|recourse|recours|denegar|denied|refusé)",
    "intent": "get_general_info",
    "response_es": "⚖️ **Apelaciones y Recursos**\n\nSi tu solicitud fue denegada:\n\n1️⃣ **Plazo:** 15 días hábiles desde la notificación\n2️⃣ **Documentación:** Copia de la denegación + nuevas pruebas\n3️⃣ **Presentación:** En la misma oficina que denegó\n\n📋 **El recurso debe incluir:**\n• Motivos de la apelación\n• Documentación adicional\n• Solicitud formal escrita\n\n💡 Se recomienda asesoría legal para casos complejos.",
    "response_fr": "⚖️ **Appels et Recours**\n\nSi votre demande a été refusée:\n\n1️⃣ **Délai:** 15 jours ouvrables depuis la notification\n2️⃣ **Documentation:** Copie du refus + nouvelles preuves\n3️⃣ **Présentation:** Dans le même bureau qui a refusé\n\n📋 **Le recours doit inclure:**\n• Motifs de l'appel\n• Documentation supplémentaire\n• Demande formelle écrite\n\n💡 Conseil juridique recommandé pour les cas complexes.",
    "response_en": "⚖️ **Appeals and Recourse**\n\nIf your application was denied:\n\n1️⃣ **Deadline:** 15 business days from notification\n2️⃣ **Documentation:** Copy of denial + new evidence\n3️⃣ **Submission:** At the same office that denied\n\n📋 **The appeal must include:**\n• Grounds for appeal\n• Additional documentation\n• Formal written request\n\n💡 Legal advice recommended for complex cases.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"Usar calculadora\"]",
    "actions": null,
    "keywords": "[\"get_general_info\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-proc-assistance",
    "question_pattern": "(ayuda|help|aide|asistencia|assistance|soporte|support|contacto|contact)",
    "intent": "get_general_info",
    "response_es": "🆘 **Asistencia y Ayuda**\n\n¿Necesitas ayuda con tus trámites?\n\n📞 **Línea de atención:** [Número disponible en oficinas]\n✉️ **Email:** info@taxasge.gq\n🏛️ **Atención presencial:** Oficinas gubernamentales\n\n**Este asistente puede ayudarte con:**\n✅ Información sobre servicios\n✅ Requisitos y documentos\n✅ Costos y plazos\n✅ Ubicación de oficinas\n\n💡 Para trámites urgentes, acude directamente a la oficina.",
    "response_fr": "🆘 **Assistance et Aide**\n\nBesoin d'aide avec vos démarches?\n\n📞 **Ligne d'assistance:** [Numéro disponible dans les bureaux]\n✉️ **Email:** info@taxasge.gq\n🏛️ **Assistance en personne:** Bureaux gouvernementaux\n\n**Cet assistant peut vous aider avec:**\n✅ Informations sur les services\n✅ Exigences et documents\n✅ Coûts et délais\n✅ Emplacement des bureaux\n\n💡 Pour les démarches urgentes, rendez-vous directement au bureau.",
    "response_en": "🆘 **Assistance and Help**\n\nNeed help with your procedures?\n\n📞 **Helpline:** [Number available at offices]\n✉️ **Email:** info@taxasge.gq\n🏛️ **In-person assistance:** Government offices\n\n**This assistant can help you with:**\n✅ Service information\n✅ Requirements and documents\n✅ Costs and deadlines\n✅ Office locations\n\n💡 For urgent procedures, go directly to the office.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"Usar calculadora\"]",
    "actions": null,
    "keywords": "[\"get_general_info\"]",
    "priority": 8,
    "is_active": 1
  },
  {
    "id": "faq-proc-renewals",
    "question_pattern": "(renovacion|renewal|renouvellement|renovar|renew|renouveler|extender|extend|prolonger)",
    "intent": "get_general_info",
    "response_es": "🔄 **Renovaciones**\n\nPara renovar documentos o licencias:\n\n⏰ **Cuándo renovar:**\n• Antes de la fecha de vencimiento\n• Algunos servicios permiten renovación 60 días antes\n\n💰 **Costos:**\n• Generalmente 20-30% menos que expedición nueva\n• Verifica la ficha de cada servicio\n\n📋 **Documentos comunes:**\n• Documento vencido o por vencer\n• DNI vigente\n• Comprobante de pago\n\n💡 Evita multas renovando a tiempo.",
    "response_fr": "🔄 **Renouvellements**\n\nPour renouveler documents ou licences:\n\n⏰ **Quand renouveler:**\n• Avant la date d'expiration\n• Certains services permettent renouvellement 60 jours avant\n\n💰 **Coûts:**\n• Généralement 20-30% moins cher que nouvelle expédition\n• Vérifiez la fiche de chaque service\n\n📋 **Documents courants:**\n• Document expiré ou sur le point d'expirer\n• DNI en vigueur\n• Justificatif de paiement\n\n💡 Évitez les amendes en renouvelant à temps.",
    "response_en": "🔄 **Renewals**\n\nTo renew documents or licenses:\n\n⏰ **When to renew:**\n• Before expiration date\n• Some services allow renewal 60 days early\n\n💰 **Costs:**\n• Generally 20-30% less than new issuance\n• Check each service details\n\n📋 **Common documents:**\n• Expired or expiring document\n• Valid DNI\n• Payment receipt\n\n💡 Avoid fines by renewing on time.",
    "follow_up_suggestions": "[\"Buscar servicios\",\"Ver servicios populares\",\"Usar calculadora\"]",
    "actions": null,
    "keywords": "[\"get_general_info\"]",
    "priority": 8,
    "is_active": 1
  }
];
