-- Generated by deploy/scripts/extract_seeds.py — DO NOT EDIT
-- Table: public.workflow_supplement_config
-- Rows:  6
-- Generated: 2026-05-09T21:57:29.404098+00:00

BEGIN;
INSERT INTO public."workflow_supplement_config" ("id", "workflow_code", "supplement_code", "quantity_per_request", "is_required", "is_active", "created_at", "updated_at")
  VALUES (1, 'RESIDENCIA_PRIMERA_VEZ', 'CEDULA_PERSONAL', 1, true, true, '2025-12-27T18:11:38.315804+00:00'::timestamptz, '2026-01-16T13:00:53.815557+00:00'::timestamptz)
  ON CONFLICT ("id") DO UPDATE SET "workflow_code" = EXCLUDED."workflow_code", "supplement_code" = EXCLUDED."supplement_code", "quantity_per_request" = EXCLUDED."quantity_per_request", "is_required" = EXCLUDED."is_required", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at", "updated_at" = EXCLUDED."updated_at";
INSERT INTO public."workflow_supplement_config" ("id", "workflow_code", "supplement_code", "quantity_per_request", "is_required", "is_active", "created_at", "updated_at")
  VALUES (2, 'RESIDENCIA_PRIMERA_VEZ', 'POLIZA', 1, true, true, '2025-12-27T18:11:38.315804+00:00'::timestamptz, '2026-01-16T13:00:53.815557+00:00'::timestamptz)
  ON CONFLICT ("id") DO UPDATE SET "workflow_code" = EXCLUDED."workflow_code", "supplement_code" = EXCLUDED."supplement_code", "quantity_per_request" = EXCLUDED."quantity_per_request", "is_required" = EXCLUDED."is_required", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at", "updated_at" = EXCLUDED."updated_at";
INSERT INTO public."workflow_supplement_config" ("id", "workflow_code", "supplement_code", "quantity_per_request", "is_required", "is_active", "created_at", "updated_at")
  VALUES (3, 'RESIDENCIA_RENOVACION', 'CEDULA_PERSONAL', 1, true, true, '2025-12-27T18:11:38.315804+00:00'::timestamptz, '2026-01-16T13:00:53.815557+00:00'::timestamptz)
  ON CONFLICT ("id") DO UPDATE SET "workflow_code" = EXCLUDED."workflow_code", "supplement_code" = EXCLUDED."supplement_code", "quantity_per_request" = EXCLUDED."quantity_per_request", "is_required" = EXCLUDED."is_required", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at", "updated_at" = EXCLUDED."updated_at";
INSERT INTO public."workflow_supplement_config" ("id", "workflow_code", "supplement_code", "quantity_per_request", "is_required", "is_active", "created_at", "updated_at")
  VALUES (4, 'RESIDENCIA_RENOVACION', 'POLIZA', 1, true, true, '2025-12-27T18:11:38.315804+00:00'::timestamptz, '2026-01-16T13:00:53.815557+00:00'::timestamptz)
  ON CONFLICT ("id") DO UPDATE SET "workflow_code" = EXCLUDED."workflow_code", "supplement_code" = EXCLUDED."supplement_code", "quantity_per_request" = EXCLUDED."quantity_per_request", "is_required" = EXCLUDED."is_required", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at", "updated_at" = EXCLUDED."updated_at";
INSERT INTO public."workflow_supplement_config" ("id", "workflow_code", "supplement_code", "quantity_per_request", "is_required", "is_active", "created_at", "updated_at")
  VALUES (5, 'CONDUCIR_NUEVO', 'CEDULA_PERSONAL', 1, true, true, '2025-12-27T18:11:38.315804+00:00'::timestamptz, '2026-01-16T13:00:53.815557+00:00'::timestamptz)
  ON CONFLICT ("id") DO UPDATE SET "workflow_code" = EXCLUDED."workflow_code", "supplement_code" = EXCLUDED."supplement_code", "quantity_per_request" = EXCLUDED."quantity_per_request", "is_required" = EXCLUDED."is_required", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at", "updated_at" = EXCLUDED."updated_at";
INSERT INTO public."workflow_supplement_config" ("id", "workflow_code", "supplement_code", "quantity_per_request", "is_required", "is_active", "created_at", "updated_at")
  VALUES (6, 'CONDUCIR_RENOVACION', 'CEDULA_PERSONAL', 1, true, true, '2025-12-27T18:11:38.315804+00:00'::timestamptz, '2026-01-16T13:00:53.815557+00:00'::timestamptz)
  ON CONFLICT ("id") DO UPDATE SET "workflow_code" = EXCLUDED."workflow_code", "supplement_code" = EXCLUDED."supplement_code", "quantity_per_request" = EXCLUDED."quantity_per_request", "is_required" = EXCLUDED."is_required", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at", "updated_at" = EXCLUDED."updated_at";

COMMIT;
