-- Generated by deploy/scripts/extract_seeds.py — DO NOT EDIT
-- Table: public.tariff_supplements
-- Rows:  3
-- Generated: 2026-05-09T21:57:29.544237+00:00

BEGIN;
INSERT INTO public."tariff_supplements" ("id", "code", "name_es", "amount", "currency", "legal_reference", "effective_from", "effective_to", "is_active", "created_by", "created_at", "updated_by", "updated_at")
  VALUES (1, 'CEDULA_PERSONAL', 'Cédula Personal', 1500.00, 'XAF', 'Ley de Tasas Fiscales', '2025-12-27'::date, NULL, true, NULL, '2025-12-27T18:11:38.315804+00:00'::timestamptz, NULL, '2025-12-27T18:11:38.315804+00:00'::timestamptz)
  ON CONFLICT ("id") DO UPDATE SET "code" = EXCLUDED."code", "name_es" = EXCLUDED."name_es", "amount" = EXCLUDED."amount", "currency" = EXCLUDED."currency", "legal_reference" = EXCLUDED."legal_reference", "effective_from" = EXCLUDED."effective_from", "effective_to" = EXCLUDED."effective_to", "is_active" = EXCLUDED."is_active", "created_by" = EXCLUDED."created_by", "created_at" = EXCLUDED."created_at", "updated_by" = EXCLUDED."updated_by", "updated_at" = EXCLUDED."updated_at";
INSERT INTO public."tariff_supplements" ("id", "code", "name_es", "amount", "currency", "legal_reference", "effective_from", "effective_to", "is_active", "created_by", "created_at", "updated_by", "updated_at")
  VALUES (2, 'POLIZA', 'Póliza', 1000.00, 'XAF', 'Ley de Tasas Fiscales', '2025-12-27'::date, NULL, true, NULL, '2025-12-27T18:11:38.315804+00:00'::timestamptz, NULL, '2025-12-27T18:11:38.315804+00:00'::timestamptz)
  ON CONFLICT ("id") DO UPDATE SET "code" = EXCLUDED."code", "name_es" = EXCLUDED."name_es", "amount" = EXCLUDED."amount", "currency" = EXCLUDED."currency", "legal_reference" = EXCLUDED."legal_reference", "effective_from" = EXCLUDED."effective_from", "effective_to" = EXCLUDED."effective_to", "is_active" = EXCLUDED."is_active", "created_by" = EXCLUDED."created_by", "created_at" = EXCLUDED."created_at", "updated_by" = EXCLUDED."updated_by", "updated_at" = EXCLUDED."updated_at";
INSERT INTO public."tariff_supplements" ("id", "code", "name_es", "amount", "currency", "legal_reference", "effective_from", "effective_to", "is_active", "created_by", "created_at", "updated_by", "updated_at")
  VALUES (3, 'TIMBRE_FISCAL', 'Timbre Fiscal', 500.00, 'XAF', 'Ley de Tasas Fiscales', '2025-12-27'::date, NULL, true, NULL, '2025-12-27T18:11:38.315804+00:00'::timestamptz, NULL, '2025-12-27T18:11:38.315804+00:00'::timestamptz)
  ON CONFLICT ("id") DO UPDATE SET "code" = EXCLUDED."code", "name_es" = EXCLUDED."name_es", "amount" = EXCLUDED."amount", "currency" = EXCLUDED."currency", "legal_reference" = EXCLUDED."legal_reference", "effective_from" = EXCLUDED."effective_from", "effective_to" = EXCLUDED."effective_to", "is_active" = EXCLUDED."is_active", "created_by" = EXCLUDED."created_by", "created_at" = EXCLUDED."created_at", "updated_by" = EXCLUDED."updated_by", "updated_at" = EXCLUDED."updated_at";

COMMIT;
