-- Generated by deploy/scripts/extract_seeds.py — DO NOT EDIT
-- Table: public.valid_workflow_codes
-- Rows:  37
-- Generated: 2026-05-09T21:57:30.988301+00:00

BEGIN;
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('PASAPORTE_NUEVO', NULL, 'NUEVO', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('PASAPORTE_RENOVACION', 'PASAPORTE_NUEVO', 'RENOVACION', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('PASAPORTE_PERDIDA', 'PASAPORTE_NUEVO', 'PERDIDA', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('PASAPORTE_ROBO', 'PASAPORTE_NUEVO', 'ROBO', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('PASAPORTE_DETERIORO', 'PASAPORTE_NUEVO', 'DETERIORO', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('CONDUCIR_NUEVO', NULL, 'NUEVO', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('CONDUCIR_CANJE', 'CONDUCIR_NUEVO', 'CANJE', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('CONDUCIR_RENOVACION', 'CONDUCIR_NUEVO', 'RENOVACION', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('CONDUCIR_DUPLICADO', 'CONDUCIR_NUEVO', 'DUPLICADO', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('CONDUCIR_EXTENSION', 'CONDUCIR_NUEVO', 'EXTENSION', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('CONTRATO_OBRA', NULL, 'OBRA', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('CONTRATO_SERVICIO', 'CONTRATO_OBRA', 'SERVICIO', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('CONTRATO_SUMINISTRO', 'CONTRATO_OBRA', 'SUMINISTRO', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('CONTRATO_CONCESION', 'CONTRATO_OBRA', 'CONCESION', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('CONTRATO_JOINT_VENTURE', 'CONTRATO_OBRA', 'JOINT_VENTURE', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('CONTRATO_ARRENDAMIENTO', 'CONTRATO_OBRA', 'ARRENDAMIENTO', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('CONTRATO_OTRO', 'CONTRATO_OBRA', 'OTRO', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('PRORROGA_VISADO', NULL, 'PRORROGA', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('VISADO_ALTERNATIVO', 'PRORROGA_VISADO', 'ALTERNATIVO', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('PERMANENCIA_EXTRANJERIA', 'PRORROGA_VISADO', 'PERMANENCIA', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('SALIDA_VISADO_VENCIDO', 'PRORROGA_VISADO', 'SALIDA_VENCIDO', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('RESIDENCIA_PRIMERA_VEZ', NULL, 'PRIMERA_VEZ', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('RESIDENCIA_RENOVACION', 'RESIDENCIA_PRIMERA_VEZ', 'RENOVACION', true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('VEHICULO_PRIMERA_MATRICULACION', NULL, NULL, true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('VEHICULO_TRANSFERENCIA', NULL, NULL, true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('VEHICULO_RENOVACION_ITV', NULL, NULL, true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('VEHICULO_RENOVACION_CUVE', NULL, NULL, true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('VEHICULO_DUPLICADO_PERMISO', NULL, NULL, true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('VEHICULO_DUPLICADO_CUVE', NULL, NULL, true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('VEHICULO_CAMBIO_CARACTERISTICAS', NULL, NULL, true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('FP_VERIFICACION_FUNCIONARIO', NULL, NULL, true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('FP_CARNET_FUNCIONARIO', NULL, NULL, true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('FP_PROMOCION_ADMINISTRATIVA', NULL, NULL, true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('FP_PERMISO_EXTRAORDINARIO', NULL, NULL, true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('FP_CERTIFICADO_ADMINISTRATIVO', NULL, NULL, true, '2026-03-07T13:09:26.907194+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('FIELD_INSPECTION', NULL, 'FIELD', true, '2026-04-07T17:49:13.885432+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";
INSERT INTO public."valid_workflow_codes" ("code", "base_code", "resolution_key", "is_active", "created_at")
  VALUES ('BUNDLE_PAYMENT', NULL, 'BUNDLE', true, '2026-04-12T14:34:32.838631+00:00'::timestamptz)
  ON CONFLICT ("code") DO UPDATE SET "base_code" = EXCLUDED."base_code", "resolution_key" = EXCLUDED."resolution_key", "is_active" = EXCLUDED."is_active", "created_at" = EXCLUDED."created_at";

COMMIT;
