# -*- coding: utf-8 -*-
"""
Repository tests for ServiceRequestRepository.create() bundle integrity.

Plan: .claude/plans/BUNDLE_DEBUG_PHASE1_PLAN.md §3.2

Validates the fix for migration 291 trigger fn_enforce_bundle_sr_integrity:
BUNDLE_PAYMENT / FIELD_INSPECTION service_requests must include
commercial_license_id + fiscal_year at INSERT time.

Each test runs inside a transaction with automatic ROLLBACK so the real
staging DB is not polluted. Uses asyncpg directly against Supabase via
backend/.env DATABASE_URL.
"""

import sys
from pathlib import Path

import asyncpg
import pytest
import pytest_asyncio

BACKEND_ROOT = Path(__file__).parent.parent.parent.parent
sys.path.insert(0, str(BACKEND_ROOT))

from app.modules.service_requests.repositories.service_request_repository import (  # noqa: E402
    ServiceRequestRepository,
)

pytestmark = pytest.mark.asyncio


def load_database_url() -> str:
    env_path = BACKEND_ROOT / ".env"
    with open(env_path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip().startswith("DATABASE_URL="):
                return line.strip().split("=", 1)[1]
    raise RuntimeError("DATABASE_URL not found in backend/.env")


# ═══════════════════════════════════════════════════════════════
# Fixtures
# ═══════════════════════════════════════════════════════════════


@pytest_asyncio.fixture(scope="function")
async def conn():
    """Connection with outer transaction rollback — zero side effects on DB."""
    c = await asyncpg.connect(load_database_url())
    tr = c.transaction()
    await tr.start()
    try:
        yield c
    finally:
        await tr.rollback()
        await c.close()


@pytest_asyncio.fixture(scope="function")
async def bundle_fixture(conn):
    """Fetch a real commercial_license + owner user so we have a valid
    (license_id, fiscal_year, bundle_id, zone_id, user_id) tuple for tests.
    """
    lic = await conn.fetchrow(
        """
        SELECT id, company_id, bundle_id, zone_id, fiscal_year
        FROM commercial_licenses
        WHERE status IN ('open', 'overdue')
        LIMIT 1
        """
    )
    if not lic:
        pytest.skip("No payable commercial_license available for tests")

    owner = await conn.fetchrow(
        """
        SELECT u.id
        FROM user_company_roles ucr
        JOIN users u ON u.id = ucr.user_id
        WHERE ucr.company_id = $1
          AND ucr.role = 'company_owner'
          AND ucr.is_active = true
        LIMIT 1
        """,
        lic["company_id"],
    )
    if not owner:
        # Fallback: any citizen user (tests only need a valid user_id FK).
        owner = await conn.fetchrow(
            "SELECT id FROM users WHERE role = 'citizen' LIMIT 1"
        )
    if not owner:
        pytest.skip("No suitable user available")

    return {
        "license_id": lic["id"],
        "company_id": lic["company_id"],
        "bundle_id": lic["bundle_id"],
        "zone_id": lic["zone_id"],
        "fiscal_year": lic["fiscal_year"],
        "user_id": owner["id"],
    }


# ═══════════════════════════════════════════════════════════════
# T1 — BUNDLE_PAYMENT with all required fields → INSERT succeeds
# ═══════════════════════════════════════════════════════════════


async def test_create_bundle_payment_with_all_fields_succeeds(conn, bundle_fixture):
    repo = ServiceRequestRepository()

    result = await repo.create(
        db=conn,
        user_id=bundle_fixture["user_id"],
        workflow_code="BUNDLE_PAYMENT",
        form_data={"license_id": str(bundle_fixture["license_id"])},
        company_id=bundle_fixture["company_id"],
        commercial_license_id=bundle_fixture["license_id"],
        fiscal_year=bundle_fixture["fiscal_year"],
        bundle_id=bundle_fixture["bundle_id"],
        zone_id=bundle_fixture["zone_id"],
    )

    assert result["id"] is not None
    assert result["workflow_code"] == "BUNDLE_PAYMENT"
    assert result["commercial_license_id"] == bundle_fixture["license_id"]
    assert result["fiscal_year"] == bundle_fixture["fiscal_year"]
    assert result["bundle_id"] == bundle_fixture["bundle_id"]
    assert result["zone_id"] == bundle_fixture["zone_id"]
    # source defaults to 'citizen_wizard' when not passed explicitly
    assert result["source"] == "citizen_wizard"
    # Auto-generated by trg_sr_auto_reference
    assert result["reference"] is not None
    assert len(result["reference"]) > 0


# ═══════════════════════════════════════════════════════════════
# T2 — BUNDLE_PAYMENT without commercial_license_id → fail fast ValueError
# ═══════════════════════════════════════════════════════════════


async def test_create_bundle_payment_without_license_id_raises(conn, bundle_fixture):
    repo = ServiceRequestRepository()

    with pytest.raises(ValueError, match="BUNDLE_SR_MISSING_LICENSE_ID"):
        await repo.create(
            db=conn,
            user_id=bundle_fixture["user_id"],
            workflow_code="BUNDLE_PAYMENT",
            form_data={},
            fiscal_year=bundle_fixture["fiscal_year"],
        )


# ═══════════════════════════════════════════════════════════════
# T3 — BUNDLE_PAYMENT without fiscal_year → fail fast ValueError
# ═══════════════════════════════════════════════════════════════


async def test_create_bundle_payment_without_fiscal_year_raises(conn, bundle_fixture):
    repo = ServiceRequestRepository()

    with pytest.raises(ValueError, match="BUNDLE_SR_MISSING_FISCAL_YEAR"):
        await repo.create(
            db=conn,
            user_id=bundle_fixture["user_id"],
            workflow_code="BUNDLE_PAYMENT",
            form_data={},
            commercial_license_id=bundle_fixture["license_id"],
        )


# ═══════════════════════════════════════════════════════════════
# T4 — FIELD_INSPECTION follows the same rules
# ═══════════════════════════════════════════════════════════════


async def test_create_field_inspection_enforces_bundle_fields(conn, bundle_fixture):
    repo = ServiceRequestRepository()

    with pytest.raises(ValueError, match="BUNDLE_SR_MISSING_LICENSE_ID"):
        await repo.create(
            db=conn,
            user_id=bundle_fixture["user_id"],
            workflow_code="FIELD_INSPECTION",
            form_data={},
            fiscal_year=bundle_fixture["fiscal_year"],
            source="field_inspection",
        )


# ═══════════════════════════════════════════════════════════════
# T5 — Non-bundle workflow: guard is a no-op
# ═══════════════════════════════════════════════════════════════


async def test_create_non_bundle_workflow_without_license_id_succeeds(
    conn, bundle_fixture
):
    repo = ServiceRequestRepository()

    result = await repo.create(
        db=conn,
        user_id=bundle_fixture["user_id"],
        workflow_code="PASAPORTE_NUEVO",
        form_data={"test": "value"},
    )

    assert result["id"] is not None
    assert result["workflow_code"] == "PASAPORTE_NUEVO"
    assert result["commercial_license_id"] is None
    assert result["fiscal_year"] is None


# ═══════════════════════════════════════════════════════════════
# T6 — Partial UNIQUE index idx_sr_commercial_license_unique
#      prevents two bundle SRs pointing to the same license
# ═══════════════════════════════════════════════════════════════


async def test_create_bundle_payment_duplicate_license_raises_unique(
    conn, bundle_fixture
):
    repo = ServiceRequestRepository()

    # First INSERT must succeed
    first = await repo.create(
        db=conn,
        user_id=bundle_fixture["user_id"],
        workflow_code="BUNDLE_PAYMENT",
        form_data={},
        commercial_license_id=bundle_fixture["license_id"],
        fiscal_year=bundle_fixture["fiscal_year"],
        bundle_id=bundle_fixture["bundle_id"],
        zone_id=bundle_fixture["zone_id"],
    )
    assert first["id"] is not None

    # Second INSERT on the SAME commercial_license_id must be rejected
    # by the partial unique index idx_sr_commercial_license_unique.
    with pytest.raises(asyncpg.UniqueViolationError):
        await repo.create(
            db=conn,
            user_id=bundle_fixture["user_id"],
            workflow_code="BUNDLE_PAYMENT",
            form_data={},
            commercial_license_id=bundle_fixture["license_id"],
            fiscal_year=bundle_fixture["fiscal_year"],
            bundle_id=bundle_fixture["bundle_id"],
            zone_id=bundle_fixture["zone_id"],
        )
