#!/usr/bin/env python3
"""docker-local provider — Phase A.5.5 of DEPLOY_SYSTEM_PLAN.

Generates a docker-compose.yml at the repo root that brings up:
  - Postgres (with persistent volume)
  - Redis
  - Backend (FastAPI / uvicorn)
  - Frontend (Next.js)

Secrets are NOT bound through Cloud Secret Manager here. Instead, they
must be present in a local .env.secrets file (gitignored). The compose
file maps them to backend env vars.

Usage
-----
    # Validate prereqs (docker installed, compose available).
    python deploy/providers/docker_local.py --config=deploy/config.yaml --validate

    # Show the generated docker-compose.yml content.
    python deploy/providers/docker_local.py --config=deploy/config.yaml --plan

    # Write docker-compose.local.yml + start containers.
    python deploy/providers/docker_local.py --config=deploy/config.yaml --apply

Exit codes
----------
0  Success.
1  Validation error (docker missing, secrets file missing in --apply mode).
2  Subprocess error (docker compose up failed).
3  YAML / file error.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

PROVIDERS_DIR = Path(__file__).resolve().parent
DEPLOY_DIR = PROVIDERS_DIR.parent
SCRIPTS_DIR = DEPLOY_DIR / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR))

import validate_config as vc  # noqa: E402

REPO_ROOT = DEPLOY_DIR.parent
DEFAULT_CONFIG = DEPLOY_DIR / "config.yaml"
COMPOSE_FILE = REPO_ROOT / "docker-compose.local.yml"
SECRETS_FILE = REPO_ROOT / ".env.secrets"  # local-only, gitignored


# ---------------------------------------------------------------------------
# Prereq checks
# ---------------------------------------------------------------------------

def find_docker() -> str | None:
    return shutil.which("docker")


def docker_compose_available() -> bool:
    """True if `docker compose` (v2 plugin) works."""
    docker = find_docker()
    if not docker:
        return False
    proc = subprocess.run(
        [docker, "compose", "version"],
        capture_output=True, text=True, check=False,
    )
    return proc.returncode == 0


# ---------------------------------------------------------------------------
# Compose file generator
# ---------------------------------------------------------------------------

def generate_compose(cfg: vc.DeployConfig) -> str:
    """Build a docker-compose.yml string from the deploy config."""
    backend_port = cfg.docker_local.backend_port
    frontend_port = cfg.docker_local.frontend_port
    pg_image = cfg.docker_local.postgres_image
    pg_volume = cfg.docker_local.postgres_volume
    redis_image = cfg.docker_local.redis_image

    return f"""# Generated by deploy/providers/docker_local.py — DO NOT EDIT MANUALLY.
# Edit deploy/config.yaml and re-run the provider.

version: "3.9"

services:
  postgres:
    image: {pg_image}
    environment:
      POSTGRES_DB: {cfg.meta.project_name}
      POSTGRES_USER: {cfg.meta.project_name}
      POSTGRES_PASSWORD: ${{POSTGRES_PASSWORD:-localdev}}
    volumes:
      - {pg_volume}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "{cfg.meta.project_name}"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: {redis_image}
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./packages/backend
    env_file:
      - ./.env.secrets
      - ./packages/backend/.env.deploy.gen
    environment:
      DATABASE_URL: postgresql://{cfg.meta.project_name}:${{POSTGRES_PASSWORD:-localdev}}@postgres:5432/{cfg.meta.project_name}
      REDIS_URL: redis://redis:6379/0
      ENVIRONMENT: {cfg.meta.environment}
      PORT: {backend_port}
    ports:
      - "{backend_port}:{backend_port}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./packages/web
      args:
        NEXT_PUBLIC_API_URL: http://localhost:{backend_port}
        NEXT_PUBLIC_BUILD_VERSION: {cfg.meta.version}
        NEXT_PUBLIC_ENVIRONMENT: {cfg.meta.environment}
    env_file:
      - ./packages/web/.env.deploy.gen
    ports:
      - "{frontend_port}:3000"
    depends_on:
      - backend

volumes:
  {pg_volume}:
"""


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--validate", action="store_true")
    mode.add_argument("--plan", action="store_true")
    mode.add_argument("--apply", action="store_true")
    args = parser.parse_args(argv)

    if not args.config.exists():
        print(f"ERROR: config not found: {args.config}", file=sys.stderr)
        return 3

    raw = vc.load_yaml(args.config)
    try:
        cfg = vc.DeployConfig.model_validate(raw)
    except Exception as e:
        print(f"ERROR: config validation failed:\n{e}", file=sys.stderr)
        return 1

    # 1. Prereqs
    print(f"=== Prerequisites ===")
    docker = find_docker()
    if not docker:
        print("[FAIL] docker not found on PATH")
        if not args.plan:
            return 1
    else:
        print(f"[OK] docker: {docker}")
    if not docker_compose_available():
        print("[FAIL] docker compose plugin not available")
        if not args.plan:
            return 1
    else:
        print("[OK] docker compose v2 available")

    if args.validate:
        print("\n[OK] Prereqs validated. Use --plan to see compose file content.")
        return 0

    # 2. Generate compose
    compose_text = generate_compose(cfg)

    if args.plan:
        print(f"\n=== Generated {COMPOSE_FILE.name} ===")
        print(compose_text)
        return 0

    # 3. Apply
    if not SECRETS_FILE.exists():
        print(
            f"ERROR: missing secrets file: {SECRETS_FILE}\n"
            f"       Create it with the required env vars (DATABASE_URL is "
            f"injected automatically; you still need JWT_SECRET_KEY, "
            f"GEMINI_API_KEY, etc.).",
            file=sys.stderr,
        )
        return 1

    COMPOSE_FILE.write_text(compose_text, encoding="utf-8")
    print(f"[OK] Wrote {COMPOSE_FILE}")

    print("\n=== Starting containers ===")
    proc = subprocess.run(
        [docker, "compose", "-f", str(COMPOSE_FILE), "up", "-d", "--build"],
        cwd=REPO_ROOT,
        check=False,
    )
    if proc.returncode != 0:
        print(f"ERROR: docker compose up failed (exit {proc.returncode})",
              file=sys.stderr)
        return 2

    print("\n[OK] Stack up. Check status:")
    print(f"  docker compose -f {COMPOSE_FILE.name} ps")
    print(f"  Backend:  http://localhost:{cfg.docker_local.backend_port}")
    print(f"  Frontend: http://localhost:{cfg.docker_local.frontend_port}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
