-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.adjustment_reasons (
  id integer NOT NULL DEFAULT nextval('adjustment_reasons_id_seq'::regclass),
  reason_code character varying NOT NULL UNIQUE,
  name_es text NOT NULL,
  name_fr text,
  name_en text,
  description text,
  category character varying NOT NULL CHECK (category::text = ANY (ARRAY['exoneration'::character varying, 'reduction'::character varying, 'error_correction'::character varying, 'special_regime'::character varying, 'administrative'::character varying, 'other'::character varying]::text[])),
  requires_supervisor_approval boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT adjustment_reasons_pkey PRIMARY KEY (id)
);
CREATE TABLE public.agent_performance_stats (
  agent_id integer NOT NULL,
  ministry_id integer NOT NULL,
  current_month_processed integer DEFAULT 0,
  current_month_approved integer DEFAULT 0,
  current_month_rejected integer DEFAULT 0,
  current_month_escalated integer DEFAULT 0,
  avg_processing_minutes numeric,
  avg_lock_duration_minutes numeric,
  sla_respected_count integer DEFAULT 0,
  sla_missed_count integer DEFAULT 0,
  sla_respect_percentage numeric DEFAULT 
CASE
    WHEN ((sla_respected_count + sla_missed_count) = 0) THEN (0)::numeric
    ELSE (((sla_respected_count)::numeric / ((sla_respected_count + sla_missed_count))::numeric) * (100)::numeric)
END,
  current_active_locks integer DEFAULT 0,
  max_concurrent_locks integer DEFAULT 0,
  last_action_at timestamp with time zone,
  last_login_at timestamp with time zone,
  stats_period_start date DEFAULT CURRENT_DATE,
  stats_period_end date,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT agent_performance_stats_pkey PRIMARY KEY (agent_id),
  CONSTRAINT agent_performance_stats_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.ministry_agents(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  entity_type character varying NOT NULL,
  entity_id character varying NOT NULL,
  action character varying NOT NULL,
  old_values jsonb,
  new_values jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.bank_configurations (
  id integer NOT NULL DEFAULT nextval('bank_configurations_id_seq'::regclass),
  bank_code character varying NOT NULL UNIQUE CHECK (bank_code::text = ANY (ARRAY['BANGE'::character varying, 'BGFI'::character varying, 'CCEIBANK'::character varying, 'SGBGE'::character varying, 'ECOBANK'::character varying]::text[])),
  bank_name text NOT NULL,
  api_endpoint text,
  api_version character varying,
  api_key_encrypted text,
  webhook_secret text,
  treasury_account_number character varying NOT NULL,
  is_active boolean DEFAULT true,
  supports_webhooks boolean DEFAULT false,
  supports_direct_integration boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bank_configurations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bank_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bank_code character varying NOT NULL CHECK (bank_code::text = ANY (ARRAY['BANGE'::character varying, 'BGFI'::character varying, 'CCEIBANK'::character varying, 'SGBGE'::character varying, 'ECOBANK'::character varying]::text[])),
  bank_reference character varying NOT NULL,
  bank_transaction_date timestamp with time zone NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency character varying NOT NULL DEFAULT 'XAF'::character varying,
  account_number character varying,
  account_holder_name text,
  payment_id uuid,
  status character varying NOT NULL DEFAULT 'unreconciled'::character varying CHECK (status::text = ANY (ARRAY['unreconciled'::character varying, 'reconciled'::character varying, 'disputed'::character varying, 'reversed'::character varying]::text[])),
  raw_data jsonb,
  reconciled_at timestamp with time zone,
  reconciled_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bank_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT bank_transactions_reconciled_by_fkey FOREIGN KEY (reconciled_by) REFERENCES public.users(id),
  CONSTRAINT fk_bank_transactions_payment FOREIGN KEY (payment_id) REFERENCES public.payments(id)
);
CREATE TABLE public.calculation_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  fiscal_service_code character varying NOT NULL CHECK (fiscal_service_code::text ~ '^T-[0-9]{3}$'::text),
  calculation_type character varying NOT NULL CHECK (calculation_type::text = ANY (ARRAY['expedition'::character varying, 'renewal'::character varying]::text[])),
  input_parameters jsonb NOT NULL,
  calculated_amount numeric NOT NULL,
  calculation_details jsonb DEFAULT '{}'::jsonb,
  saved_for_later boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT calculation_history_pkey PRIMARY KEY (id),
  CONSTRAINT calculation_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT calculation_history_fiscal_service_code_fkey FOREIGN KEY (fiscal_service_code) REFERENCES public.fiscal_services(service_code)
);
CREATE TABLE public.categories (
  id integer NOT NULL DEFAULT nextval('categories_id_seq'::regclass),
  category_code character varying NOT NULL UNIQUE CHECK (category_code::text ~ '^C-[0-9]{3}$'::text),
  sector_id integer,
  ministry_id integer,
  service_type USER-DEFINED,
  name_es character varying NOT NULL,
  description_es text,
  display_order integer DEFAULT 0,
  icon character varying,
  color character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.sectors(id),
  CONSTRAINT categories_ministry_id_fkey FOREIGN KEY (ministry_id) REFERENCES public.ministries(id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tax_id character varying NOT NULL UNIQUE,
  legal_name character varying NOT NULL,
  trade_name character varying,
  primary_sector_id integer,
  address text,
  city character varying,
  phone character varying,
  email character varying,
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT companies_pkey PRIMARY KEY (id),
  CONSTRAINT companies_primary_sector_id_fkey FOREIGN KEY (primary_sector_id) REFERENCES public.sectors(id)
);
CREATE TABLE public.declaration_amount_adjustments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tax_declaration_id uuid NOT NULL,
  original_amount numeric NOT NULL,
  adjusted_amount numeric NOT NULL,
  difference numeric DEFAULT (adjusted_amount - original_amount),
  percentage_change numeric DEFAULT 
CASE
    WHEN (original_amount = (0)::numeric) THEN (0)::numeric
    ELSE abs((((adjusted_amount - original_amount) / original_amount) * (100)::numeric))
END,
  requires_supervisor_approval boolean DEFAULT (abs(((adjusted_amount - original_amount) / NULLIF(original_amount, (0)::numeric))) > 0.20),
  adjustment_reason_id integer,
  adjustment_reason_custom text,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'cancelled'::character varying]::text[])),
  adjusted_by uuid NOT NULL,
  approved_by uuid,
  approved_at timestamp with time zone,
  approval_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT declaration_amount_adjustments_pkey PRIMARY KEY (id),
  CONSTRAINT declaration_amount_adjustments_tax_declaration_id_fkey FOREIGN KEY (tax_declaration_id) REFERENCES public.tax_declarations(id),
  CONSTRAINT declaration_amount_adjustments_adjustment_reason_id_fkey FOREIGN KEY (adjustment_reason_id) REFERENCES public.adjustment_reasons(id),
  CONSTRAINT declaration_amount_adjustments_adjusted_by_fkey FOREIGN KEY (adjusted_by) REFERENCES public.users(id),
  CONSTRAINT declaration_amount_adjustments_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.declaration_corrections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  original_declaration_id uuid NOT NULL,
  rectificative_declaration_id uuid NOT NULL,
  correction_type character varying NOT NULL CHECK (correction_type::text = ANY (ARRAY['amount_adjustment'::character varying, 'data_error'::character varying, 'omission'::character varying, 'calculation_error'::character varying, 'tax_regime_change'::character varying, 'other'::character varying]::text[])),
  original_amount numeric,
  rectified_amount numeric,
  difference numeric DEFAULT (rectified_amount - original_amount),
  changes_detail jsonb NOT NULL,
  correction_reason text NOT NULL,
  supporting_documents ARRAY,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'cancelled'::character varying]::text[])),
  approved_by uuid,
  approved_at timestamp with time zone,
  approval_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT declaration_corrections_pkey PRIMARY KEY (id),
  CONSTRAINT declaration_corrections_original_declaration_id_fkey FOREIGN KEY (original_declaration_id) REFERENCES public.tax_declarations(id),
  CONSTRAINT declaration_corrections_rectificative_declaration_id_fkey FOREIGN KEY (rectificative_declaration_id) REFERENCES public.tax_declarations(id),
  CONSTRAINT declaration_corrections_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.declaration_data_generic (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tax_declaration_id uuid NOT NULL UNIQUE,
  form_template_id uuid,
  declaration_subtype character varying NOT NULL,
  data jsonb NOT NULL,
  calculated_amount numeric,
  adjusted_amount numeric,
  adjustment_reason_id integer,
  adjustment_reason_custom text,
  adjusted_by uuid,
  adjusted_at timestamp with time zone,
  final_amount numeric DEFAULT COALESCE(adjusted_amount, calculated_amount),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT declaration_data_generic_pkey PRIMARY KEY (id),
  CONSTRAINT declaration_data_generic_tax_declaration_id_fkey FOREIGN KEY (tax_declaration_id) REFERENCES public.tax_declarations(id),
  CONSTRAINT declaration_data_generic_form_template_id_fkey FOREIGN KEY (form_template_id) REFERENCES public.form_templates(id),
  CONSTRAINT declaration_data_generic_adjustment_reason_id_fkey FOREIGN KEY (adjustment_reason_id) REFERENCES public.adjustment_reasons(id),
  CONSTRAINT declaration_data_generic_adjusted_by_fkey FOREIGN KEY (adjusted_by) REFERENCES public.users(id)
);
CREATE TABLE public.declaration_irpf_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tax_declaration_id uuid NOT NULL UNIQUE,
  revenus_salaires numeric DEFAULT 0,
  revenus_activites_professionnelles numeric DEFAULT 0,
  revenus_capitaux_mobiliers numeric DEFAULT 0,
  revenus_capitaux_immobiliers numeric DEFAULT 0,
  revenus_autres numeric DEFAULT 0,
  total_revenus_bruts numeric DEFAULT ((((revenus_salaires + revenus_activites_professionnelles) + revenus_capitaux_mobiliers) + revenus_capitaux_immobiliers) + revenus_autres),
  deductions_charges_famille numeric DEFAULT 0,
  deductions_cotisations_sociales numeric DEFAULT 0,
  deductions_dons numeric DEFAULT 0,
  deductions_autres numeric DEFAULT 0,
  total_deductions numeric DEFAULT (((deductions_charges_famille + deductions_cotisations_sociales) + deductions_dons) + deductions_autres),
  base_liquidable numeric DEFAULT (((((revenus_salaires + revenus_activites_professionnelles) + revenus_capitaux_mobiliers) + revenus_capitaux_immobiliers) + revenus_autres) - (((deductions_charges_famille + deductions_cotisations_sociales) + deductions_dons) + deductions_autres)),
  tipo_gravamen numeric DEFAULT 0,
  calculated_amount numeric DEFAULT (((((((revenus_salaires + revenus_activites_professionnelles) + revenus_capitaux_mobiliers) + revenus_capitaux_immobiliers) + revenus_autres) - (((deductions_charges_famille + deductions_cotisations_sociales) + deductions_dons) + deductions_autres)) * tipo_gravamen) / (100)::numeric),
  adjusted_amount numeric,
  adjustment_reason_id integer,
  adjustment_reason_custom text,
  adjusted_by uuid,
  adjusted_at timestamp with time zone,
  final_amount numeric DEFAULT COALESCE(adjusted_amount, (((((((revenus_salaires + revenus_activites_professionnelles) + revenus_capitaux_mobiliers) + revenus_capitaux_immobiliers) + revenus_autres) - (((deductions_charges_famille + deductions_cotisations_sociales) + deductions_dons) + deductions_autres)) * tipo_gravamen) / (100)::numeric)),
  retenues_a_la_source numeric DEFAULT 0,
  acomptes_verses numeric DEFAULT 0,
  interes_demora numeric DEFAULT 0,
  recargos numeric DEFAULT 0,
  sanciones numeric DEFAULT 0,
  total_a_ingresar numeric DEFAULT (((((COALESCE(adjusted_amount, (((((((revenus_salaires + revenus_activites_professionnelles) + revenus_capitaux_mobiliers) + revenus_capitaux_immobiliers) + revenus_autres) - (((deductions_charges_famille + deductions_cotisations_sociales) + deductions_dons) + deductions_autres)) * tipo_gravamen) / (100)::numeric)) - retenues_a_la_source) - acomptes_verses) + interes_demora) + recargos) + sanciones),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT declaration_irpf_data_pkey PRIMARY KEY (id),
  CONSTRAINT declaration_irpf_data_tax_declaration_id_fkey FOREIGN KEY (tax_declaration_id) REFERENCES public.tax_declarations(id),
  CONSTRAINT declaration_irpf_data_adjustment_reason_id_fkey FOREIGN KEY (adjustment_reason_id) REFERENCES public.adjustment_reasons(id),
  CONSTRAINT declaration_irpf_data_adjusted_by_fkey FOREIGN KEY (adjusted_by) REFERENCES public.users(id)
);
CREATE TABLE public.declaration_iva_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tax_declaration_id uuid NOT NULL UNIQUE,
  iva_dev_01_base numeric DEFAULT 0,
  iva_dev_02_tipo numeric DEFAULT 15.00,
  iva_dev_03_cuota numeric DEFAULT ((iva_dev_01_base * iva_dev_02_tipo) / (100)::numeric),
  iva_dev_04_base numeric DEFAULT 0,
  iva_dev_05_tipo numeric DEFAULT 6.00,
  iva_dev_06_cuota numeric DEFAULT ((iva_dev_04_base * iva_dev_05_tipo) / (100)::numeric),
  iva_dev_07_base numeric DEFAULT 0,
  iva_dev_08_tipo numeric DEFAULT 1.50,
  iva_dev_09_cuota numeric DEFAULT ((iva_dev_07_base * iva_dev_08_tipo) / (100)::numeric),
  iva_dev_10_base numeric DEFAULT 0,
  iva_dev_11_tipo numeric DEFAULT 15.00,
  iva_dev_12_cuota numeric DEFAULT ((iva_dev_10_base * iva_dev_11_tipo) / (100)::numeric),
  iva_dev_13_base_exonerada numeric DEFAULT 0,
  iva_dev_014_total numeric DEFAULT (((((iva_dev_01_base * iva_dev_02_tipo) / (100)::numeric) + ((iva_dev_04_base * iva_dev_05_tipo) / (100)::numeric)) + ((iva_dev_07_base * iva_dev_08_tipo) / (100)::numeric)) + ((iva_dev_10_base * iva_dev_11_tipo) / (100)::numeric)),
  iva_ded_01_operaciones_interiores numeric DEFAULT 0,
  iva_ded_02_importaciones numeric DEFAULT 0,
  iva_ded_03_adquisiciones_intracomunitarias numeric DEFAULT 0,
  iva_ded_04_bienes_inversion numeric DEFAULT 0,
  iva_ded_05_regularizacion_inversiones numeric DEFAULT 0,
  iva_ded_06_creditos_periodos_anteriores numeric DEFAULT 0,
  iva_ded_07_total numeric DEFAULT (((((iva_ded_01_operaciones_interiores + iva_ded_02_importaciones) + iva_ded_03_adquisiciones_intracomunitarias) + iva_ded_04_bienes_inversion) + iva_ded_05_regularizacion_inversiones) + iva_ded_06_creditos_periodos_anteriores),
  calculated_amount numeric DEFAULT ((((((iva_dev_01_base * iva_dev_02_tipo) / (100)::numeric) + ((iva_dev_04_base * iva_dev_05_tipo) / (100)::numeric)) + ((iva_dev_07_base * iva_dev_08_tipo) / (100)::numeric)) + ((iva_dev_10_base * iva_dev_11_tipo) / (100)::numeric)) - (((((iva_ded_01_operaciones_interiores + iva_ded_02_importaciones) + iva_ded_03_adquisiciones_intracomunitarias) + iva_ded_04_bienes_inversion) + iva_ded_05_regularizacion_inversiones) + iva_ded_06_creditos_periodos_anteriores)),
  adjusted_amount numeric,
  adjustment_reason_id integer,
  adjustment_reason_custom text,
  adjusted_by uuid,
  adjusted_at timestamp with time zone,
  final_amount numeric DEFAULT COALESCE(adjusted_amount, ((((((iva_dev_01_base * iva_dev_02_tipo) / (100)::numeric) + ((iva_dev_04_base * iva_dev_05_tipo) / (100)::numeric)) + ((iva_dev_07_base * iva_dev_08_tipo) / (100)::numeric)) + ((iva_dev_10_base * iva_dev_11_tipo) / (100)::numeric)) - (((((iva_ded_01_operaciones_interiores + iva_ded_02_importaciones) + iva_ded_03_adquisiciones_intracomunitarias) + iva_ded_04_bienes_inversion) + iva_ded_05_regularizacion_inversiones) + iva_ded_06_creditos_periodos_anteriores))),
  interes_demora numeric DEFAULT 0,
  recargos numeric DEFAULT 0,
  sanciones numeric DEFAULT 0,
  total_a_ingresar numeric DEFAULT (((COALESCE(adjusted_amount, ((((((iva_dev_01_base * iva_dev_02_tipo) / (100)::numeric) + ((iva_dev_04_base * iva_dev_05_tipo) / (100)::numeric)) + ((iva_dev_07_base * iva_dev_08_tipo) / (100)::numeric)) + ((iva_dev_10_base * iva_dev_11_tipo) / (100)::numeric)) - (((((iva_ded_01_operaciones_interiores + iva_ded_02_importaciones) + iva_ded_03_adquisiciones_intracomunitarias) + iva_ded_04_bienes_inversion) + iva_ded_05_regularizacion_inversiones) + iva_ded_06_creditos_periodos_anteriores))) + interes_demora) + recargos) + sanciones),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT declaration_iva_data_pkey PRIMARY KEY (id),
  CONSTRAINT declaration_iva_data_tax_declaration_id_fkey FOREIGN KEY (tax_declaration_id) REFERENCES public.tax_declarations(id),
  CONSTRAINT declaration_iva_data_adjustment_reason_id_fkey FOREIGN KEY (adjustment_reason_id) REFERENCES public.adjustment_reasons(id),
  CONSTRAINT declaration_iva_data_adjusted_by_fkey FOREIGN KEY (adjusted_by) REFERENCES public.users(id)
);
CREATE TABLE public.declaration_petroliferos_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tax_declaration_id uuid NOT NULL UNIQUE,
  petroleum_declaration_subtype character varying NOT NULL CHECK (petroleum_declaration_subtype::text = ANY (ARRAY['imp_prod_fmi'::character varying, 'imp_prod_ivs'::character varying, 'residentes_3'::character varying, 'residentes_5'::character varying, 'no_residentes_10'::character varying, 'cuota_min_petrolera'::character varying]::text[])),
  base_imponible numeric DEFAULT 0,
  tipo_gravamen numeric DEFAULT 0,
  cantidad_producto numeric,
  unidad_medida character varying,
  precio_unitario numeric,
  calculated_amount numeric DEFAULT ((base_imponible * tipo_gravamen) / (100)::numeric),
  adjusted_amount numeric,
  adjustment_reason_id integer,
  adjustment_reason_custom text,
  adjusted_by uuid,
  adjusted_at timestamp with time zone,
  final_amount numeric DEFAULT COALESCE(adjusted_amount, ((base_imponible * tipo_gravamen) / (100)::numeric)),
  interes_demora numeric DEFAULT 0,
  recargos numeric DEFAULT 0,
  sanciones numeric DEFAULT 0,
  total_a_ingresar numeric DEFAULT (((COALESCE(adjusted_amount, ((base_imponible * tipo_gravamen) / (100)::numeric)) + interes_demora) + recargos) + sanciones),
  subtype_specific_data jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT declaration_petroliferos_data_pkey PRIMARY KEY (id),
  CONSTRAINT declaration_petroliferos_data_tax_declaration_id_fkey FOREIGN KEY (tax_declaration_id) REFERENCES public.tax_declarations(id),
  CONSTRAINT declaration_petroliferos_data_adjustment_reason_id_fkey FOREIGN KEY (adjustment_reason_id) REFERENCES public.adjustment_reasons(id),
  CONSTRAINT declaration_petroliferos_data_adjusted_by_fkey FOREIGN KEY (adjusted_by) REFERENCES public.users(id)
);
CREATE TABLE public.document_templates (
  id integer NOT NULL DEFAULT nextval('document_templates_id_seq'::regclass),
  template_code character varying NOT NULL UNIQUE CHECK (template_code::text ~ '^[A-Z0-9_]+$'::text),
  document_name_es character varying NOT NULL,
  description_es text,
  category character varying,
  validity_duration_months integer CHECK (validity_duration_months > 0),
  validity_notes text,
  usage_count integer NOT NULL DEFAULT 0 CHECK (usage_count >= 0),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by integer,
  CONSTRAINT document_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.document_templates_backup_20251017 (
  id integer,
  template_code character varying,
  document_name_es character varying,
  description_es text,
  category character varying,
  validity_duration_months integer,
  validity_notes text,
  usage_count integer,
  is_active boolean,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  created_by integer
);
CREATE TABLE public.entity_translations (
  entity_type USER-DEFINED NOT NULL,
  entity_code character varying NOT NULL,
  language_code character varying NOT NULL CHECK (language_code::text = ANY (ARRAY['fr'::character varying, 'en'::character varying]::text[])),
  field_name character varying NOT NULL CHECK (field_name::text = ANY (ARRAY['name'::character varying, 'description'::character varying, 'instructions'::character varying]::text[])),
  translation_text text NOT NULL,
  translation_source character varying DEFAULT 'manual'::character varying CHECK (translation_source::text = ANY (ARRAY['manual'::character varying, 'import'::character varying, 'ai'::character varying, 'google_translate'::character varying]::text[])),
  translation_quality numeric CHECK (translation_quality >= 0::numeric AND translation_quality <= 1::numeric),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT entity_translations_pkey PRIMARY KEY (entity_type, entity_code, language_code, field_name)
);
CREATE TABLE public.fiscal_service_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  fiscal_service_id integer NOT NULL,
  uploaded_file_id uuid,
  ocr_extraction_id uuid,
  status character varying NOT NULL DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'submitted'::character varying, 'under_review'::character varying, 'approved'::character varying, 'rejected'::character varying, 'completed'::character varying]::text[])),
  numero_nota character varying,
  nom_demandeur text,
  concepto_pago text,
  periode character varying,
  montant_chiffre numeric,
  montant_lettre text,
  date_expiration date,
  additional_data jsonb,
  final_amount numeric DEFAULT montant_chiffre,
  currency character varying DEFAULT 'XAF'::character varying,
  payment_id uuid,
  supporting_documents ARRAY DEFAULT '{}'::uuid[],
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  review_notes text,
  submitted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fiscal_service_data_pkey PRIMARY KEY (id),
  CONSTRAINT fiscal_service_data_fiscal_service_id_fkey FOREIGN KEY (fiscal_service_id) REFERENCES public.fiscal_services(id),
  CONSTRAINT fiscal_service_data_uploaded_file_id_fkey FOREIGN KEY (uploaded_file_id) REFERENCES public.uploaded_files(id),
  CONSTRAINT fiscal_service_data_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fiscal_service_data_ocr_extraction_id_fkey FOREIGN KEY (ocr_extraction_id) REFERENCES public.ocr_extraction_results(id),
  CONSTRAINT fiscal_service_data_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id),
  CONSTRAINT fiscal_service_data_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.fiscal_services (
  id integer NOT NULL DEFAULT nextval('fiscal_services_id_seq'::regclass),
  service_code character varying NOT NULL UNIQUE CHECK (service_code::text ~ '^T-[0-9]{3}$'::text),
  category_id integer NOT NULL,
  name_es character varying NOT NULL,
  description_es text,
  service_type USER-DEFINED NOT NULL,
  calculation_method USER-DEFINED NOT NULL,
  tasa_expedicion numeric DEFAULT 0.0,
  expedition_formula text,
  expedition_unit_measure character varying,
  tasa_renovacion numeric DEFAULT 0.0,
  renewal_formula text,
  renewal_unit_measure character varying,
  calculation_config jsonb DEFAULT '{}'::jsonb,
  rate_tiers jsonb DEFAULT '[]'::jsonb,
  base_percentage numeric,
  percentage_of character varying,
  unit_rate numeric,
  unit_type character varying,
  parent_service_id integer,
  tier_group_name character varying,
  is_tier_component boolean DEFAULT false,
  validity_period_months integer,
  renewal_frequency_months integer,
  grace_period_days integer DEFAULT 0,
  late_penalty_percentage numeric,
  late_penalty_fixed numeric,
  penalty_calculation_rules jsonb DEFAULT '{}'::jsonb,
  eligibility_criteria jsonb DEFAULT '{}'::jsonb,
  exemption_conditions jsonb DEFAULT '[]'::jsonb,
  legal_reference text,
  regulatory_articles ARRAY,
  tariff_effective_from date NOT NULL DEFAULT CURRENT_DATE,
  tariff_effective_to date,
  status USER-DEFINED DEFAULT 'active'::service_status_enum,
  priority integer DEFAULT 0,
  complexity_level integer DEFAULT 1 CHECK (complexity_level >= 1 AND complexity_level <= 5),
  processing_time_days integer DEFAULT 1,
  view_count integer DEFAULT 0,
  calculation_count integer DEFAULT 0,
  payment_count integer DEFAULT 0,
  favorite_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT fiscal_services_pkey PRIMARY KEY (id),
  CONSTRAINT fiscal_services_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT fiscal_services_parent_service_id_fkey FOREIGN KEY (parent_service_id) REFERENCES public.fiscal_services(id)
);
CREATE TABLE public.form_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_category character varying NOT NULL CHECK (template_category::text = ANY (ARRAY['tax_declaration'::character varying, 'fiscal_service'::character varying]::text[])),
  template_code character varying NOT NULL UNIQUE,
  name_es text NOT NULL,
  name_fr text,
  name_en text,
  description text,
  declaration_type USER-DEFINED,
  fiscal_service_id integer,
  version integer NOT NULL DEFAULT 1,
  template_schema jsonb NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT form_templates_pkey PRIMARY KEY (id),
  CONSTRAINT form_templates_fiscal_service_id_fkey FOREIGN KEY (fiscal_service_id) REFERENCES public.fiscal_services(id)
);
CREATE TABLE public.import_batch_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  batch_id uuid NOT NULL,
  row_number integer NOT NULL CHECK (row_number > 0),
  raw_data jsonb NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'validating'::character varying, 'valid'::character varying, 'invalid'::character varying, 'processing'::character varying, 'success'::character varying, 'failed'::character varying]::text[])),
  created_entity_id uuid,
  created_entity_type character varying,
  validation_errors jsonb,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  processed_at timestamp with time zone,
  CONSTRAINT import_batch_items_pkey PRIMARY KEY (id),
  CONSTRAINT import_batch_items_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.import_batches(id)
);
CREATE TABLE public.import_batches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  uploaded_by uuid NOT NULL,
  file_name character varying NOT NULL,
  file_path text NOT NULL,
  file_size_bytes bigint,
  import_type character varying NOT NULL CHECK (import_type::text = ANY (ARRAY['declarations_iva'::character varying, 'declarations_irpf'::character varying, 'declarations_petroliferos'::character varying, 'declarations_generic'::character varying, 'payments'::character varying, 'companies'::character varying, 'users'::character varying]::text[])),
  total_rows integer NOT NULL CHECK (total_rows > 0),
  rows_processed integer DEFAULT 0 CHECK (rows_processed >= 0),
  rows_success integer DEFAULT 0 CHECK (rows_success >= 0),
  rows_failed integer DEFAULT 0 CHECK (rows_failed >= 0),
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'validating'::character varying, 'processing'::character varying, 'completed'::character varying, 'partial'::character varying, 'failed'::character varying]::text[])),
  validation_errors jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  CONSTRAINT import_batches_pkey PRIMARY KEY (id),
  CONSTRAINT import_batches_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.ministries (
  id integer NOT NULL DEFAULT nextval('ministries_id_seq'::regclass),
  ministry_code character varying NOT NULL UNIQUE CHECK (ministry_code::text ~ '^M-[0-9]{3}$'::text),
  name_es character varying NOT NULL,
  description_es text,
  display_order integer DEFAULT 0,
  icon character varying,
  color character varying,
  website_url character varying,
  contact_email character varying,
  contact_phone character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ministries_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ministry_agents (
  id integer NOT NULL DEFAULT nextval('ministry_agents_id_seq'::regclass),
  user_id uuid NOT NULL,
  ministry_id integer NOT NULL,
  agent_role character varying NOT NULL DEFAULT 'validator'::character varying CHECK (agent_role::text = ANY (ARRAY['validator'::character varying, 'senior_validator'::character varying, 'supervisor'::character varying, 'ministry_admin'::character varying]::text[])),
  can_approve_unlimited boolean DEFAULT false,
  max_approval_amount numeric,
  can_escalate boolean DEFAULT true,
  can_assign_tasks boolean DEFAULT false,
  is_active boolean DEFAULT true,
  is_backup_agent boolean DEFAULT false,
  backup_for_agent_id integer,
  working_hours_start time without time zone DEFAULT '08:00:00'::time without time zone,
  working_hours_end time without time zone DEFAULT '17:00:00'::time without time zone,
  working_days ARRAY DEFAULT ARRAY[1, 2, 3, 4, 5],
  assigned_at timestamp with time zone DEFAULT now(),
  assigned_by uuid,
  deactivated_at timestamp with time zone,
  deactivated_by uuid,
  deactivation_reason text,
  CONSTRAINT ministry_agents_pkey PRIMARY KEY (id),
  CONSTRAINT ministry_agents_deactivated_by_fkey FOREIGN KEY (deactivated_by) REFERENCES public.users(id),
  CONSTRAINT ministry_agents_ministry_id_fkey FOREIGN KEY (ministry_id) REFERENCES public.ministries(id),
  CONSTRAINT ministry_agents_backup_for_agent_id_fkey FOREIGN KEY (backup_for_agent_id) REFERENCES public.ministry_agents(id),
  CONSTRAINT ministry_agents_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.users(id),
  CONSTRAINT ministry_agents_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.ministry_validation_config (
  id integer NOT NULL DEFAULT nextval('ministry_validation_config_id_seq'::regclass),
  ministry_id integer NOT NULL,
  service_type USER-DEFINED NOT NULL,
  auto_approval_enabled boolean DEFAULT false,
  auto_approval_max_amount numeric DEFAULT 0,
  auto_approval_conditions jsonb DEFAULT '{}'::jsonb,
  auto_approval_max_per_day integer DEFAULT 10,
  auto_approval_max_per_user_month integer DEFAULT 5,
  auto_approval_business_hours_only boolean DEFAULT true,
  target_review_hours integer DEFAULT 24,
  warning_threshold_hours integer DEFAULT 18,
  escalation_hours integer DEFAULT 72,
  max_lock_duration_minutes integer DEFAULT 120,
  mandatory_document_types ARRAY DEFAULT '{}'::text[],
  optional_document_types ARRAY DEFAULT '{}'::text[],
  business_rules jsonb DEFAULT '{}'::jsonb,
  validation_checklist jsonb DEFAULT '[]'::jsonb,
  notify_on_submission boolean DEFAULT true,
  notify_on_escalation boolean DEFAULT true,
  notification_email text,
  is_active boolean DEFAULT true,
  effective_from date DEFAULT CURRENT_DATE,
  effective_to date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT ministry_validation_config_pkey PRIMARY KEY (id),
  CONSTRAINT ministry_validation_config_ministry_id_fkey FOREIGN KEY (ministry_id) REFERENCES public.ministries(id),
  CONSTRAINT ministry_validation_config_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT ministry_validation_config_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.ocr_extraction_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  uploaded_file_id uuid NOT NULL,
  ocr_engine USER-DEFINED NOT NULL,
  extracted_data jsonb NOT NULL,
  confidence_score numeric CHECK (confidence_score >= 0::numeric AND confidence_score <= 1::numeric),
  processing_time_ms integer,
  tesseract_version character varying,
  language_used character varying DEFAULT 'spa+fra+eng'::character varying,
  status character varying NOT NULL DEFAULT 'pending_validation'::character varying CHECK (status::text = ANY (ARRAY['pending_validation'::character varying, 'validated'::character varying, 'rejected'::character varying, 'corrected'::character varying]::text[])),
  validated_by uuid,
  validated_at timestamp with time zone,
  validation_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ocr_extraction_results_pkey PRIMARY KEY (id),
  CONSTRAINT ocr_extraction_results_uploaded_file_id_fkey FOREIGN KEY (uploaded_file_id) REFERENCES public.uploaded_files(id),
  CONSTRAINT ocr_extraction_results_validated_by_fkey FOREIGN KEY (validated_by) REFERENCES public.users(id)
);
CREATE TABLE public.payment_installments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_plan_id uuid NOT NULL,
  installment_number integer NOT NULL CHECK (installment_number > 0),
  amount_due numeric NOT NULL CHECK (amount_due > 0::numeric),
  amount_paid numeric NOT NULL DEFAULT 0 CHECK (amount_paid >= 0::numeric),
  remaining_amount numeric DEFAULT (amount_due - amount_paid),
  due_date date NOT NULL,
  grace_period_days integer NOT NULL DEFAULT 7,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'paid'::character varying, 'overdue'::character varying, 'partially_paid'::character varying, 'cancelled'::character varying]::text[])),
  late_fee numeric NOT NULL DEFAULT 0 CHECK (late_fee >= 0::numeric),
  late_fee_rate numeric NOT NULL DEFAULT 0.05,
  late_fee_applied_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  paid_at timestamp with time zone,
  CONSTRAINT payment_installments_pkey PRIMARY KEY (id),
  CONSTRAINT payment_installments_payment_plan_id_fkey FOREIGN KEY (payment_plan_id) REFERENCES public.payment_plans(id)
);
CREATE TABLE public.payment_lock_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_id uuid NOT NULL,
  agent_id integer NOT NULL,
  locked_at timestamp with time zone NOT NULL,
  unlocked_at timestamp with time zone,
  lock_duration_minutes integer DEFAULT (EXTRACT(epoch FROM (unlocked_at - locked_at)) / (60)::numeric),
  unlock_reason character varying CHECK (unlock_reason::text = ANY (ARRAY['completed_work'::character varying, 'manual_unlock'::character varying, 'auto_expired'::character varying, 'escalated'::character varying, 'reassigned'::character varying]::text[])),
  actions_performed jsonb DEFAULT '[]'::jsonb,
  final_action USER-DEFINED,
  CONSTRAINT payment_lock_history_pkey PRIMARY KEY (id),
  CONSTRAINT payment_lock_history_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.service_payments(id),
  CONSTRAINT payment_lock_history_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.ministry_agents(id)
);
CREATE TABLE public.payment_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tax_declaration_id uuid NOT NULL UNIQUE,
  total_amount numeric NOT NULL CHECK (total_amount > 0::numeric),
  currency character varying NOT NULL DEFAULT 'XAF'::character varying,
  number_of_installments integer NOT NULL CHECK (number_of_installments >= 1 AND number_of_installments <= 12),
  installment_amount numeric NOT NULL CHECK (installment_amount > 0::numeric),
  first_installment_due_date date NOT NULL,
  installment_frequency character varying NOT NULL DEFAULT 'monthly'::character varying CHECK (installment_frequency::text = ANY (ARRAY['monthly'::character varying, 'quarterly'::character varying, 'custom'::character varying]::text[])),
  total_paid numeric NOT NULL DEFAULT 0 CHECK (total_paid >= 0::numeric),
  remaining_balance numeric DEFAULT (total_amount - total_paid),
  status character varying NOT NULL DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'completed'::character varying, 'defaulted'::character varying, 'cancelled'::character varying]::text[])),
  approved_by uuid,
  approved_at timestamp with time zone,
  approval_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT payment_plans_pkey PRIMARY KEY (id),
  CONSTRAINT payment_plans_tax_declaration_id_fkey FOREIGN KEY (tax_declaration_id) REFERENCES public.tax_declarations(id),
  CONSTRAINT payment_plans_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.payment_receipts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_id uuid NOT NULL,
  file_path text NOT NULL UNIQUE,
  file_size_bytes bigint,
  receipt_number character varying NOT NULL UNIQUE,
  qr_code_data text,
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  generated_by uuid,
  CONSTRAINT payment_receipts_pkey PRIMARY KEY (id),
  CONSTRAINT payment_receipts_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES public.users(id),
  CONSTRAINT payment_receipts_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id)
);
CREATE TABLE public.payment_validation_audit (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_id uuid NOT NULL,
  agent_id integer,
  agent_user_id uuid,
  action USER-DEFINED NOT NULL,
  from_status USER-DEFINED,
  to_status USER-DEFINED,
  comment text,
  validation_details jsonb,
  documents_requested ARRAY,
  rejection_reasons ARRAY,
  ip_address inet,
  user_agent text,
  session_id character varying,
  action_duration_seconds integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_validation_audit_pkey PRIMARY KEY (id),
  CONSTRAINT payment_validation_audit_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.service_payments(id),
  CONSTRAINT payment_validation_audit_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.ministry_agents(id),
  CONSTRAINT payment_validation_audit_agent_user_id_fkey FOREIGN KEY (agent_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  fiscal_service_id integer,
  tax_declaration_id uuid,
  payment_plan_id uuid,
  installment_id uuid,
  base_amount numeric NOT NULL CHECK (base_amount > 0::numeric),
  penalties numeric NOT NULL DEFAULT 0 CHECK (penalties >= 0::numeric),
  interest numeric NOT NULL DEFAULT 0 CHECK (interest >= 0::numeric),
  amount numeric DEFAULT ((base_amount + penalties) + interest),
  currency character varying NOT NULL DEFAULT 'XAF'::character varying CHECK (currency::text = ANY (ARRAY['XAF'::character varying, 'EUR'::character varying, 'USD'::character varying]::text[])),
  payment_type USER-DEFINED NOT NULL DEFAULT 'full'::payment_type_enum,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::payment_status_enum,
  payment_method character varying NOT NULL DEFAULT 'bank_transfer'::character varying CHECK (payment_method::text = ANY (ARRAY['bank_transfer'::character varying, 'mobile_money'::character varying, 'cash'::character varying, 'check'::character varying, 'card'::character varying]::text[])),
  bank_reference character varying UNIQUE,
  bank_transaction_id uuid,
  idempotency_key character varying NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  paid_at timestamp with time zone,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT payments_fiscal_service_id_fkey FOREIGN KEY (fiscal_service_id) REFERENCES public.fiscal_services(id),
  CONSTRAINT payments_tax_declaration_id_fkey FOREIGN KEY (tax_declaration_id) REFERENCES public.tax_declarations(id),
  CONSTRAINT payments_payment_plan_id_fkey FOREIGN KEY (payment_plan_id) REFERENCES public.payment_plans(id),
  CONSTRAINT payments_installment_id_fkey FOREIGN KEY (installment_id) REFERENCES public.payment_installments(id),
  CONSTRAINT payments_bank_transaction_id_fkey FOREIGN KEY (bank_transaction_id) REFERENCES public.bank_transactions(id)
);
CREATE TABLE public.procedure_template_steps (
  id integer NOT NULL DEFAULT nextval('procedure_template_steps_id_seq'::regclass),
  template_id integer,
  step_number integer NOT NULL CHECK (step_number > 0 AND step_number <= 100),
  description_es text NOT NULL,
  instructions_es text,
  estimated_duration_minutes integer CHECK (estimated_duration_minutes > 0),
  location_address text,
  office_hours character varying,
  requires_appointment boolean DEFAULT false,
  is_optional boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT procedure_template_steps_pkey PRIMARY KEY (id),
  CONSTRAINT procedure_template_steps_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.procedure_templates(id)
);
CREATE TABLE public.procedure_template_steps_backup_20251017 (
  id integer,
  template_id integer,
  step_number integer,
  description_es text,
  instructions_es text,
  estimated_duration_minutes integer,
  location_address text,
  office_hours character varying,
  requires_appointment boolean,
  is_optional boolean,
  created_at timestamp with time zone,
  updated_at timestamp with time zone
);
CREATE TABLE public.procedure_templates (
  id integer NOT NULL DEFAULT nextval('procedure_templates_id_seq'::regclass),
  template_code character varying NOT NULL UNIQUE CHECK (template_code::text ~ '^[A-Z0-9_]+$'::text),
  name_es character varying NOT NULL,
  description_es text,
  category character varying,
  usage_count integer NOT NULL DEFAULT 0 CHECK (usage_count >= 0),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by integer,
  CONSTRAINT procedure_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.refresh_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  token text NOT NULL UNIQUE,
  user_id uuid NOT NULL,
  session_id uuid NOT NULL,
  is_revoked boolean NOT NULL DEFAULT false,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  revoked_at timestamp with time zone,
  last_used_at timestamp with time zone,
  CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT refresh_tokens_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id)
);
CREATE TABLE public.sectors (
  id integer NOT NULL DEFAULT nextval('sectors_id_seq'::regclass),
  sector_code character varying NOT NULL UNIQUE CHECK (sector_code::text ~ '^S-[0-9]{3}$'::text),
  ministry_id integer NOT NULL,
  name_es character varying NOT NULL,
  description_es text,
  display_order integer DEFAULT 0,
  icon character varying,
  color character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sectors_pkey PRIMARY KEY (id),
  CONSTRAINT sectors_ministry_id_fkey FOREIGN KEY (ministry_id) REFERENCES public.ministries(id)
);
CREATE TABLE public.service_document_assignments (
  id integer NOT NULL DEFAULT nextval('service_document_assignments_id_seq'::regclass),
  fiscal_service_id integer,
  document_template_id integer,
  is_required_expedition boolean DEFAULT true,
  is_required_renewal boolean DEFAULT false,
  display_order integer DEFAULT 1,
  custom_notes text,
  assigned_at timestamp with time zone DEFAULT now(),
  assigned_by integer,
  CONSTRAINT service_document_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT service_document_assignments_fiscal_service_id_fkey FOREIGN KEY (fiscal_service_id) REFERENCES public.fiscal_services(id),
  CONSTRAINT service_document_assignments_document_template_id_fkey FOREIGN KEY (document_template_id) REFERENCES public.document_templates(id)
);
CREATE TABLE public.service_keywords (
  id integer NOT NULL DEFAULT nextval('service_keywords_id_seq'::regclass),
  fiscal_service_id integer NOT NULL,
  keyword character varying NOT NULL,
  language_code character varying NOT NULL CHECK (language_code::text = ANY (ARRAY['es'::character varying, 'fr'::character varying, 'en'::character varying]::text[])),
  weight integer DEFAULT 1,
  is_auto_generated boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_keywords_pkey PRIMARY KEY (id),
  CONSTRAINT service_keywords_fiscal_service_id_fkey FOREIGN KEY (fiscal_service_id) REFERENCES public.fiscal_services(id)
);
CREATE TABLE public.service_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_reference character varying NOT NULL UNIQUE,
  fiscal_service_code character varying NOT NULL CHECK (fiscal_service_code::text ~ '^T-[0-9]{3}$'::text),
  user_id uuid NOT NULL,
  company_id uuid,
  payment_type character varying NOT NULL CHECK (payment_type::text = ANY (ARRAY['expedition'::character varying, 'renewal'::character varying]::text[])),
  calculation_base numeric,
  calculation_details jsonb DEFAULT '{}'::jsonb,
  base_amount numeric NOT NULL,
  penalties numeric DEFAULT 0,
  discounts numeric DEFAULT 0,
  total_amount numeric NOT NULL,
  payment_method USER-DEFINED NOT NULL,
  currency character varying NOT NULL DEFAULT 'XAF'::character varying,
  bange_transaction_id character varying UNIQUE,
  bange_wallet_id character varying,
  status USER-DEFINED DEFAULT 'pending'::payment_status_enum,
  workflow_status USER-DEFINED DEFAULT 'submitted'::payment_workflow_status,
  paid_at timestamp with time zone,
  expires_at timestamp with time zone,
  locked_by_agent_id integer,
  locked_at timestamp with time zone,
  lock_expires_at timestamp with time zone,
  assigned_agent_id integer,
  assigned_at timestamp with time zone,
  validated_by_agent_id integer,
  validated_at timestamp with time zone,
  validation_comment text,
  validation_checklist_completed jsonb DEFAULT '{}'::jsonb,
  escalated_to_agent_id integer,
  escalated_at timestamp with time zone,
  escalation_reason text,
  escalation_level USER-DEFINED,
  sla_target_date timestamp with time zone,
  sla_warning_sent boolean DEFAULT false,
  sla_escalated boolean DEFAULT false,
  ministry_id integer,
  requires_agent_validation boolean DEFAULT true,
  auto_approval_eligible boolean DEFAULT false,
  rejection_count integer DEFAULT 0,
  resubmission_count integer DEFAULT 0,
  receipt_number character varying UNIQUE,
  receipt_url text,
  supporting_documents jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_payments_pkey PRIMARY KEY (id),
  CONSTRAINT service_payments_fiscal_service_code_fkey FOREIGN KEY (fiscal_service_code) REFERENCES public.fiscal_services(service_code),
  CONSTRAINT service_payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT service_payments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT service_payments_locked_by_agent_id_fkey FOREIGN KEY (locked_by_agent_id) REFERENCES public.ministry_agents(id),
  CONSTRAINT service_payments_assigned_agent_id_fkey FOREIGN KEY (assigned_agent_id) REFERENCES public.ministry_agents(id),
  CONSTRAINT service_payments_validated_by_agent_id_fkey FOREIGN KEY (validated_by_agent_id) REFERENCES public.ministry_agents(id),
  CONSTRAINT service_payments_escalated_to_agent_id_fkey FOREIGN KEY (escalated_to_agent_id) REFERENCES public.ministry_agents(id)
);
CREATE TABLE public.service_procedure_assignments (
  id integer NOT NULL DEFAULT nextval('service_procedure_assignments_id_seq'::regclass),
  fiscal_service_id integer,
  template_id integer,
  applies_to character varying CHECK (applies_to::text = ANY (ARRAY['expedition'::character varying, 'renewal'::character varying, 'both'::character varying]::text[])),
  display_order integer DEFAULT 1,
  custom_notes text,
  override_steps jsonb,
  assigned_at timestamp with time zone DEFAULT now(),
  assigned_by integer,
  CONSTRAINT service_procedure_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT service_procedure_assignments_fiscal_service_id_fkey FOREIGN KEY (fiscal_service_id) REFERENCES public.fiscal_services(id),
  CONSTRAINT service_procedure_assignments_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.procedure_templates(id)
);
CREATE TABLE public.service_procedure_assignments_backup_20251017 (
  id integer,
  fiscal_service_id integer,
  template_id integer,
  applies_to character varying,
  display_order integer,
  custom_notes text,
  override_steps jsonb,
  assigned_at timestamp with time zone,
  assigned_by integer
);
CREATE TABLE public.sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  status character varying NOT NULL DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'expired'::character varying, 'revoked'::character varying]::text[])),
  ip_address character varying,
  user_agent text,
  device_info jsonb,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  last_activity timestamp with time zone DEFAULT now(),
  revoked_at timestamp with time zone,
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.steps_count (
  count bigint
);
CREATE TABLE public.system_rules (
  id integer NOT NULL DEFAULT nextval('system_rules_id_seq'::regclass),
  rule_code character varying NOT NULL UNIQUE,
  rule_category character varying NOT NULL CHECK (rule_category::text = ANY (ARRAY['validation'::character varying, 'penalty'::character varying, 'exemption'::character varying, 'calculation'::character varying, 'workflow'::character varying, 'compliance'::character varying]::text[])),
  name_es text NOT NULL,
  name_fr text,
  name_en text,
  description text,
  rule_value jsonb NOT NULL,
  value_type character varying NOT NULL CHECK (value_type::text = ANY (ARRAY['number'::character varying, 'percentage'::character varying, 'date'::character varying, 'boolean'::character varying, 'string'::character varying, 'json'::character varying]::text[])),
  applies_to character varying,
  effective_from date NOT NULL DEFAULT CURRENT_DATE,
  effective_until date,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT system_rules_pkey PRIMARY KEY (id),
  CONSTRAINT system_rules_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.tax_declarations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  declaration_number character varying NOT NULL UNIQUE,
  user_id uuid NOT NULL,
  company_id uuid,
  declaration_type USER-DEFINED NOT NULL,
  fiscal_year integer NOT NULL,
  fiscal_period character varying,
  declaration_deadline date NOT NULL,
  declared_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  supporting_documents jsonb DEFAULT '[]'::jsonb,
  taxable_base numeric DEFAULT 0,
  calculated_tax numeric DEFAULT 0,
  deductions numeric DEFAULT 0,
  credits numeric DEFAULT 0,
  net_tax_due numeric DEFAULT 0,
  status USER-DEFINED DEFAULT 'draft'::declaration_status_enum,
  submitted_at timestamp with time zone,
  processed_at timestamp with time zone,
  processed_by uuid,
  taxpayer_notes text,
  processor_notes text,
  rejection_reason text,
  digital_signature text,
  signature_timestamp timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  declaration_nature character varying DEFAULT 'original'::character varying CHECK (declaration_nature::text = ANY (ARRAY['original'::character varying, 'rectificative'::character varying, 'complementary'::character varying, 'annulation'::character varying]::text[])),
  original_declaration_id uuid,
  CONSTRAINT tax_declarations_pkey PRIMARY KEY (id),
  CONSTRAINT tax_declarations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT tax_declarations_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT tax_declarations_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.users(id),
  CONSTRAINT tax_declarations_original_declaration_id_fkey FOREIGN KEY (original_declaration_id) REFERENCES public.tax_declarations(id)
);
CREATE TABLE public.translations (
  id bigint NOT NULL DEFAULT nextval('translations_id_seq'::regclass),
  category character varying NOT NULL,
  key_code character varying NOT NULL,
  context character varying,
  es text NOT NULL,
  fr text NOT NULL,
  en text NOT NULL,
  description text,
  translation_source character varying DEFAULT 'manual'::character varying,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  version integer DEFAULT 1,
  CONSTRAINT translations_pkey PRIMARY KEY (id),
  CONSTRAINT translations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT translations_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.uploaded_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  tax_declaration_id uuid,
  payment_id uuid,
  file_path text NOT NULL UNIQUE,
  file_name text NOT NULL,
  file_size_bytes bigint NOT NULL CHECK (file_size_bytes > 0),
  mime_type character varying NOT NULL,
  file_type USER-DEFINED NOT NULL,
  requires_ocr boolean NOT NULL DEFAULT false,
  ocr_status character varying DEFAULT 'pending'::character varying CHECK (ocr_status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying, 'skipped'::character varying]::text[])),
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT uploaded_files_pkey PRIMARY KEY (id),
  CONSTRAINT uploaded_files_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT uploaded_files_tax_declaration_id_fkey FOREIGN KEY (tax_declaration_id) REFERENCES public.tax_declarations(id),
  CONSTRAINT uploaded_files_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id)
);
CREATE TABLE public.user_company_roles (
  user_id uuid NOT NULL,
  company_id uuid NOT NULL,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['owner'::character varying, 'admin'::character varying, 'accountant'::character varying, 'employee'::character varying, 'viewer'::character varying]::text[])),
  is_active boolean DEFAULT true,
  assigned_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_company_roles_pkey PRIMARY KEY (user_id, company_id),
  CONSTRAINT user_company_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_company_roles_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.user_favorites (
  user_id uuid NOT NULL,
  fiscal_service_code character varying NOT NULL CHECK (fiscal_service_code::text ~ '^T-[0-9]{3}$'::text),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_favorites_pkey PRIMARY KEY (user_id, fiscal_service_code),
  CONSTRAINT user_favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_favorites_fiscal_service_code_fkey FOREIGN KEY (fiscal_service_code) REFERENCES public.fiscal_services(service_code)
);
CREATE TABLE public.user_ministry_assignments (
  user_id uuid NOT NULL,
  ministry_id integer NOT NULL,
  ministry_role character varying NOT NULL CHECK (ministry_role::text = ANY (ARRAY['agent'::character varying, 'supervisor'::character varying, 'auditor'::character varying, 'administrator'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'active'::character varying, 'suspended'::character varying, 'revoked'::character varying]::text[])),
  approved_by uuid,
  approved_at timestamp with time zone,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  assigned_by uuid NOT NULL,
  revoked_at timestamp with time zone,
  revoked_by uuid,
  revoked_reason text,
  CONSTRAINT user_ministry_assignments_pkey PRIMARY KEY (user_id, ministry_id),
  CONSTRAINT user_ministry_assignments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_ministry_assignments_ministry_id_fkey FOREIGN KEY (ministry_id) REFERENCES public.ministries(id),
  CONSTRAINT user_ministry_assignments_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT user_ministry_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.users(id),
  CONSTRAINT user_ministry_assignments_revoked_by_fkey FOREIGN KEY (revoked_by) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  full_name character varying DEFAULT (((first_name)::text || ' '::text) || (last_name)::text),
  matricule character varying UNIQUE,
  phone_number character varying,
  document_type character varying,
  document_number character varying,
  role USER-DEFINED NOT NULL DEFAULT 'citizen'::user_role_enum,
  status USER-DEFINED DEFAULT 'active'::user_status_enum,
  preferred_language character varying DEFAULT 'es'::character varying CHECK (preferred_language::text = ANY (ARRAY['es'::character varying, 'fr'::character varying, 'en'::character varying]::text[])),
  email_notifications boolean DEFAULT true,
  push_notifications boolean DEFAULT true,
  email_verified boolean DEFAULT false,
  phone_verified boolean DEFAULT false,
  last_login timestamp with time zone,
  failed_login_attempts integer DEFAULT 0,
  locked_until timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  address text,
  city character varying,
  avatar_url text,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.workflow_transitions (
  id integer NOT NULL DEFAULT nextval('workflow_transitions_id_seq'::regclass),
  from_status USER-DEFINED NOT NULL,
  to_status USER-DEFINED NOT NULL,
  allowed_roles ARRAY NOT NULL,
  requires_comment boolean DEFAULT false,
  requires_supervisor_approval boolean DEFAULT false,
  max_transition_hours integer,
  conditions jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT workflow_transitions_pkey PRIMARY KEY (id)
);