"""
Data access layer for batch_requests and batch_request_items tables.
Uses asyncpg parameterized queries ($1, $2, ...).
"""
import json
import math
from typing import Optional, List, Dict, Any
from uuid import UUID

import asyncpg
from loguru import logger

# Maximum beneficiaries per batch — configurable via env var (B-021)
import os
MAX_BENEFICIARIES_PER_BATCH = int(os.environ.get("BATCH_MAX_BENEFICIARIES", "500"))


class BatchRepository:
    """Repository for batch_requests CRUD operations."""

    # =========================================================================
    # BATCH REQUESTS
    # =========================================================================

    async def create_batch(
        self,
        db: asyncpg.Connection,
        submitted_by: UUID,
        workflow_code: str,
        solicitud_type: str = "expedicion",
        company_id: Optional[UUID] = None,
        entity_code: Optional[str] = None,
        notes: Optional[str] = None,
    ) -> Optional[Dict]:
        """Create a new batch request. Reference is auto-generated by trigger."""
        query = """
            INSERT INTO batch_requests (
                submitted_by, workflow_code, solicitud_type,
                company_id, entity_code, notes
            )
            VALUES ($1, $2, $3, $4, $5, $6)
            RETURNING *
        """
        row = await db.fetchrow(
            query,
            submitted_by,
            workflow_code,
            solicitud_type,
            company_id,
            entity_code,
            notes,
        )
        return dict(row) if row else None

    async def find_batch_by_id(
        self,
        db: asyncpg.Connection,
        batch_id: UUID,
    ) -> Optional[Dict]:
        """Find batch request by ID."""
        query = "SELECT * FROM batch_requests WHERE id = $1"
        row = await db.fetchrow(query, batch_id)
        return dict(row) if row else None

    async def find_batch_by_reference(
        self,
        db: asyncpg.Connection,
        reference: str,
    ) -> Optional[Dict]:
        """Find batch request by reference (LOT-YYYY-NNNNN)."""
        query = "SELECT * FROM batch_requests WHERE reference = $1"
        row = await db.fetchrow(query, reference)
        return dict(row) if row else None

    async def list_batches_by_user(
        self,
        db: asyncpg.Connection,
        user_id: UUID,
        status: Optional[str] = None,
        page: int = 1,
        page_size: int = 20,
    ) -> Dict:
        """List batch requests for a user with pagination."""
        conditions = ["submitted_by = $1"]
        params: List[Any] = [user_id]
        idx = 2

        if status:
            conditions.append(f"status = ${idx}")
            params.append(status)
            idx += 1

        where_clause = " AND ".join(conditions)

        # Count total
        count_query = f"SELECT COUNT(*) FROM batch_requests WHERE {where_clause}"
        total = await db.fetchval(count_query, *params)

        # Fetch page
        offset = (page - 1) * page_size
        data_query = f"""
            SELECT * FROM batch_requests
            WHERE {where_clause}
            ORDER BY created_at DESC
            LIMIT ${idx} OFFSET ${idx + 1}
        """
        params.extend([page_size, offset])
        rows = await db.fetch(data_query, *params)

        return {
            "batches": [dict(r) for r in rows],
            "total": total,
            "page": page,
            "page_size": page_size,
            "total_pages": math.ceil(total / page_size) if total > 0 else 0,
        }

    async def update_batch_status(
        self,
        db: asyncpg.Connection,
        batch_id: UUID,
        status: str,
    ) -> Optional[Dict]:
        """Update batch status."""
        query = """
            UPDATE batch_requests SET status = $2, updated_at = NOW()
            WHERE id = $1 RETURNING *
        """
        row = await db.fetchrow(query, batch_id, status)
        return dict(row) if row else None

    async def update_batch(
        self,
        db: asyncpg.Connection,
        batch_id: UUID,
        **kwargs,
    ) -> Optional[Dict]:
        """Update batch fields dynamically."""
        if not kwargs:
            return await self.find_batch_by_id(db, batch_id)

        allowed_fields = {
            "notes", "entity_code", "shared_documents",
            "per_item_amount", "total_amount", "total_items",
            "items_ready", "items_submitted", "items_completed",
            "submitted_at", "completed_at", "gateway_transaction_id",
        }
        sets = []
        params: List[Any] = [batch_id]
        idx = 2

        jsonb_fields = {"shared_documents"}

        for field, value in kwargs.items():
            if field not in allowed_fields:
                continue
            if field in jsonb_fields:
                sets.append(f"{field} = ${idx}::jsonb")
                params.append(json.dumps(value) if isinstance(value, (list, dict)) else value)
            else:
                sets.append(f"{field} = ${idx}")
                params.append(value)
            idx += 1

        if not sets:
            return await self.find_batch_by_id(db, batch_id)

        sets.append("updated_at = NOW()")
        query = f"UPDATE batch_requests SET {', '.join(sets)} WHERE id = $1 RETURNING *"
        row = await db.fetchrow(query, *params)
        return dict(row) if row else None

    async def delete_batch(
        self,
        db: asyncpg.Connection,
        batch_id: UUID,
    ) -> bool:
        """Delete a batch request (cascades to items)."""
        query = "DELETE FROM batch_requests WHERE id = $1"
        result = await db.execute(query, batch_id)
        return result == "DELETE 1"

    # =========================================================================
    # BATCH REQUEST ITEMS (Beneficiaries)
    # =========================================================================

    async def add_item(
        self,
        db: asyncpg.Connection,
        batch_id: UUID,
        beneficiary_name: str,
        beneficiary_identifier: Optional[str] = None,
        beneficiary_identifier_type: Optional[str] = None,
        beneficiary_email: Optional[str] = None,
        beneficiary_phone: Optional[str] = None,
        conditions: Optional[Dict] = None,
        item_order: Optional[int] = None,
    ) -> Dict:
        """Add a beneficiary item to a batch. INSERT + count update in transaction."""
        # Check limit before insert
        current_count = await db.fetchval(
            "SELECT total_items FROM batch_requests WHERE id = $1",
            batch_id,
        )
        if current_count is not None and current_count >= MAX_BENEFICIARIES_PER_BATCH:
            raise ValueError(
                f"Límite de {MAX_BENEFICIARIES_PER_BATCH} beneficiarios por lote alcanzado."
            )

        async with db.transaction():
            # Auto-compute item_order if not provided
            if item_order is None:
                max_order = await db.fetchval(
                    "SELECT COALESCE(MAX(item_order), -1) + 1 FROM batch_request_items WHERE batch_id = $1",
                    batch_id,
                )
                item_order = max_order

            query = """
                INSERT INTO batch_request_items (
                    batch_id, beneficiary_name, beneficiary_identifier,
                    beneficiary_identifier_type, beneficiary_email,
                    beneficiary_phone, conditions, item_order
                )
                VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb, $8)
                RETURNING *
            """
            row = await db.fetchrow(
                query,
                batch_id,
                beneficiary_name,
                beneficiary_identifier,
                beneficiary_identifier_type,
                beneficiary_email,
                beneficiary_phone,
                json.dumps(conditions) if conditions else '{}',
                item_order,
            )
            # Update total_items count on parent batch (same transaction)
            await db.execute(
                "UPDATE batch_requests SET total_items = total_items + 1, updated_at = NOW() WHERE id = $1",
                batch_id,
            )
        return dict(row)

    async def add_items_bulk(
        self,
        db: asyncpg.Connection,
        batch_id: UUID,
        items: List[Dict],
    ) -> List[Dict]:
        """Add multiple beneficiary items at once in a single transaction."""
        # Check limit before inserts
        current_count = await db.fetchval(
            "SELECT total_items FROM batch_requests WHERE id = $1",
            batch_id,
        )
        if current_count is not None and current_count + len(items) > MAX_BENEFICIARIES_PER_BATCH:
            raise ValueError(
                f"Límite de {MAX_BENEFICIARIES_PER_BATCH} beneficiarios por lote. "
                f"Actual: {current_count}, intentando agregar: {len(items)}."
            )

        created = []
        async with db.transaction():
            # Get current max order
            max_order = await db.fetchval(
                "SELECT COALESCE(MAX(item_order), -1) FROM batch_request_items WHERE batch_id = $1",
                batch_id,
            )
            current_order = max_order + 1

            for item_data in items:
                order = item_data.get("item_order", current_order)
                query = """
                    INSERT INTO batch_request_items (
                        batch_id, beneficiary_name, beneficiary_identifier,
                        beneficiary_identifier_type, beneficiary_email,
                        beneficiary_phone, conditions, item_order
                    )
                    VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb, $8)
                    RETURNING *
                """
                row = await db.fetchrow(
                    query,
                    batch_id,
                    item_data["beneficiary_name"],
                    item_data.get("beneficiary_identifier"),
                    item_data.get("beneficiary_identifier_type"),
                    item_data.get("beneficiary_email"),
                    item_data.get("beneficiary_phone"),
                    json.dumps(item_data.get("conditions", {})),
                    order,
                )
                created.append(dict(row))
                current_order += 1

            # Update total_items count (same transaction)
            await db.execute(
                "UPDATE batch_requests SET total_items = total_items + $2, updated_at = NOW() WHERE id = $1",
                batch_id,
                len(created),
            )
        return created

    async def find_item_by_id(
        self,
        db: asyncpg.Connection,
        item_id: UUID,
    ) -> Optional[Dict]:
        """Find a batch item by ID."""
        query = "SELECT * FROM batch_request_items WHERE id = $1"
        row = await db.fetchrow(query, item_id)
        return dict(row) if row else None

    async def list_items(
        self,
        db: asyncpg.Connection,
        batch_id: UUID,
        status: Optional[str] = None,
    ) -> List[Dict]:
        """List all items for a batch."""
        if status:
            query = """
                SELECT * FROM batch_request_items
                WHERE batch_id = $1 AND status = $2
                ORDER BY item_order ASC
            """
            rows = await db.fetch(query, batch_id, status)
        else:
            query = """
                SELECT * FROM batch_request_items
                WHERE batch_id = $1
                ORDER BY item_order ASC
            """
            rows = await db.fetch(query, batch_id)
        return [dict(r) for r in rows]

    async def update_item(
        self,
        db: asyncpg.Connection,
        item_id: UUID,
        **kwargs,
    ) -> Optional[Dict]:
        """Update a batch item's fields."""
        if not kwargs:
            return await self.find_item_by_id(db, item_id)

        allowed_fields = {
            "beneficiary_name", "beneficiary_identifier",
            "beneficiary_identifier_type", "beneficiary_email",
            "beneficiary_phone", "conditions", "required_documents",
            "assigned_documents", "form_data", "status",
            "item_amount", "validation_errors", "missing_documents",
            "service_request_id", "item_order",
        }
        sets = []
        params: List[Any] = [item_id]
        idx = 2

        jsonb_fields = {
            "conditions", "required_documents", "assigned_documents",
            "form_data", "validation_errors", "missing_documents",
        }

        for field, value in kwargs.items():
            if field not in allowed_fields:
                continue
            if field in jsonb_fields:
                sets.append(f"{field} = ${idx}::jsonb")
                params.append(json.dumps(value) if isinstance(value, (list, dict)) else value)
            else:
                sets.append(f"{field} = ${idx}")
                params.append(value)
            idx += 1

        if not sets:
            return await self.find_item_by_id(db, item_id)

        sets.append("updated_at = NOW()")
        query = f"UPDATE batch_request_items SET {', '.join(sets)} WHERE id = $1 RETURNING *"
        row = await db.fetchrow(query, *params)
        return dict(row) if row else None

    async def delete_item(
        self,
        db: asyncpg.Connection,
        item_id: UUID,
        batch_id: UUID,
    ) -> bool:
        """Delete a batch item and decrement total_items in transaction."""
        async with db.transaction():
            result = await db.execute(
                "DELETE FROM batch_request_items WHERE id = $1 AND batch_id = $2",
                item_id,
                batch_id,
            )
            if result == "DELETE 1":
                await db.execute(
                    "UPDATE batch_requests SET total_items = GREATEST(total_items - 1, 0), updated_at = NOW() WHERE id = $1",
                    batch_id,
                )
                return True
        return False

    async def count_items_by_status(
        self,
        db: asyncpg.Connection,
        batch_id: UUID,
    ) -> Dict[str, int]:
        """Count items grouped by status."""
        query = """
            SELECT status, COUNT(*) as cnt
            FROM batch_request_items
            WHERE batch_id = $1
            GROUP BY status
        """
        rows = await db.fetch(query, batch_id)
        return {row["status"]: row["cnt"] for row in rows}


    # ─── Agent-facing queries ───────────────────────────────────

    async def list_batches_by_entity(
        self,
        db: asyncpg.Connection,
        entity_workflows: List[str],
        status: Optional[str] = None,
        search: Optional[str] = None,
        page: int = 1,
        page_size: int = 20,
    ) -> Dict:
        """List batch requests whose workflow_code is in entity_workflows."""
        conditions = ["workflow_code = ANY($1::text[])"]
        # Only show submitted batches (PAID, IN_PROGRESS, COMPLETED)
        conditions.append("status IN ('PAID', 'IN_PROGRESS', 'COMPLETED')")
        params: List[Any] = [entity_workflows]
        idx = 2

        if status:
            conditions.append(f"status = ${idx}")
            params.append(status)
            idx += 1

        if search:
            conditions.append(f"(reference ILIKE ${idx} OR notes ILIKE ${idx})")
            params.append(f"%{search}%")
            idx += 1

        where_clause = " AND ".join(conditions)

        count_q = f"SELECT COUNT(*) FROM batch_requests WHERE {where_clause}"
        total = await db.fetchval(count_q, *params)

        offset = (page - 1) * page_size
        data_q = f"""
            SELECT * FROM batch_requests
            WHERE {where_clause}
            ORDER BY created_at DESC
            LIMIT ${idx} OFFSET ${idx + 1}
        """
        params.extend([page_size, offset])
        rows = await db.fetch(data_q, *params)

        return {
            "batches": [dict(r) for r in rows],
            "total": total,
            "page": page,
            "page_size": page_size,
            "total_pages": math.ceil(total / page_size) if total > 0 else 0,
        }

    async def get_batch_detail_for_agent(
        self,
        db: asyncpg.Connection,
        batch_id: UUID,
    ) -> Optional[Dict]:
        """Get batch with items joined to service_requests for live status."""
        batch = await self.find_batch_by_id(db, batch_id)
        if not batch:
            return None

        # Get submitter info
        user_row = await db.fetchrow(
            "SELECT first_name, last_name, email FROM users WHERE id = $1",
            batch["submitted_by"],
        )
        if user_row:
            batch["submitted_by_name"] = f"{user_row['first_name']} {user_row['last_name']}"
            batch["submitted_by_email"] = user_row["email"]
        else:
            batch["submitted_by_name"] = None
            batch["submitted_by_email"] = None

        # Get items with live SR status + agent name (single query, no N+1)
        items = await db.fetch("""
            SELECT
                bi.*,
                sr.status AS sr_status,
                sr.reference AS sr_reference,
                sr.validated_by AS sr_assigned_to_id,
                u_agent.full_name AS sr_assigned_to,
                sp.status AS sr_payment_status
            FROM batch_request_items bi
            LEFT JOIN service_requests sr ON sr.id = bi.service_request_id
            LEFT JOIN users u_agent ON u_agent.id = sr.validated_by
            LEFT JOIN service_payments sp ON sp.service_request_id = sr.id
            WHERE bi.batch_id = $1
            ORDER BY bi.item_order, bi.created_at
        """, batch_id)

        batch["items"] = []
        for item in items:
            d = dict(item)
            d["sr_status"] = d.pop("sr_status", None)
            d["sr_reference"] = d.pop("sr_reference", None)
            d["sr_payment_status"] = d.pop("sr_payment_status", None)
            d["sr_assigned_to"] = d.pop("sr_assigned_to", None)
            d.pop("sr_assigned_to_id", None)
            batch["items"].append(d)

        return batch

    async def check_and_complete_batch(
        self,
        db: asyncpg.Connection,
        batch_id: UUID,
    ) -> bool:
        """
        Check if all items in batch are finalized. If so, mark COMPLETED.
        Returns True if batch was just completed.
        """
        remaining = await db.fetchval("""
            SELECT COUNT(*) FROM service_requests
            WHERE batch_id = $1
            AND status::text NOT IN ('DOSSIER_VALIDE', 'APPROVED', 'REJECTED', 'COMPLETED', 'EXPIRED')
        """, batch_id)

        if remaining == 0:
            result = await db.execute("""
                UPDATE batch_requests
                SET status = 'COMPLETED', completed_at = NOW(), updated_at = NOW()
                WHERE id = $1 AND status != 'COMPLETED'
            """, batch_id)
            return "UPDATE 1" in result
        return False


# Singleton instance
batch_repository = BatchRepository()
