"""
Repository for service_requests table.
Data access layer following 3-tier architecture.
"""
import asyncpg
from typing import Optional, List, Dict, Any
from uuid import UUID
import json


class ServiceRequestRepository:
    """Data access layer for service_requests table"""

    async def create(
        self,
        db: asyncpg.Connection,
        user_id: UUID,
        workflow_code: str,
        solicitud_type: str = "expedicion",
        fiscal_service_id: Optional[int] = None,
        priority: str = "NORMAL",
        form_data: Optional[Dict] = None
    ) -> Dict:
        """
        Create new service request.
        Reference is auto-generated by database trigger (migration 020).
        """
        query = """
            INSERT INTO service_requests (
                user_id, workflow_code, solicitud_type,
                fiscal_service_id, priority, form_data, created_by
            )
            VALUES ($1, $2, $3, $4, $5, $6::jsonb, $1)
            RETURNING *
        """
        row = await db.fetchrow(
            query,
            user_id,
            workflow_code,
            solicitud_type,
            fiscal_service_id,
            priority,
            json.dumps(form_data) if form_data else '{}'
        )
        return self._row_to_dict(row)

    async def find_by_id(
        self,
        db: asyncpg.Connection,
        request_id: UUID
    ) -> Optional[Dict]:
        """Find service request by ID"""
        query = "SELECT * FROM service_requests WHERE id = $1"
        row = await db.fetchrow(query, request_id)
        return self._row_to_dict(row) if row else None

    async def find_by_reference(
        self,
        db: asyncpg.Connection,
        reference: str
    ) -> Optional[Dict]:
        """Find service request by reference (e.g., RES-2025-00001)"""
        query = "SELECT * FROM service_requests WHERE reference = $1"
        row = await db.fetchrow(query, reference)
        return self._row_to_dict(row) if row else None

    async def find_by_user(
        self,
        db: asyncpg.Connection,
        user_id: UUID,
        status: Optional[str] = None,
        workflow_code: Optional[str] = None,
        limit: int = 20,
        offset: int = 0
    ) -> List[Dict]:
        """List service requests for a user with optional filters"""
        conditions = ["user_id = $1"]
        params: List[Any] = [user_id]
        param_idx = 2

        if status:
            conditions.append(f"status = ${param_idx}")
            params.append(status)
            param_idx += 1

        if workflow_code:
            conditions.append(f"workflow_code = ${param_idx}")
            params.append(workflow_code)
            param_idx += 1

        where_clause = " AND ".join(conditions)
        params.extend([limit, offset])

        query = f"""
            SELECT * FROM service_requests
            WHERE {where_clause}
            ORDER BY created_at DESC
            LIMIT ${param_idx} OFFSET ${param_idx + 1}
        """
        rows = await db.fetch(query, *params)
        return [self._row_to_dict(row) for row in rows]

    async def count_by_user(
        self,
        db: asyncpg.Connection,
        user_id: UUID,
        status: Optional[str] = None
    ) -> int:
        """Count service requests for a user"""
        if status:
            query = "SELECT COUNT(*) FROM service_requests WHERE user_id = $1 AND status = $2"
            row = await db.fetchrow(query, user_id, status)
        else:
            query = "SELECT COUNT(*) FROM service_requests WHERE user_id = $1"
            row = await db.fetchrow(query, user_id)
        return row["count"]

    async def update_status(
        self,
        db: asyncpg.Connection,
        request_id: UUID,
        new_status: str,
        performed_by: UUID,
        comment: Optional[str] = None
    ) -> Dict:
        """
        Update status and create history entry.
        Uses service_request_history table for audit trail.
        """
        # Get current status
        current = await self.find_by_id(db, request_id)
        if not current:
            raise ValueError(f"Service request {request_id} not found")

        # Update status
        await db.execute(
            """UPDATE service_requests
               SET status = $2, updated_at = NOW()
               WHERE id = $1""",
            request_id, new_status
        )

        # Create history entry
        await db.execute(
            """INSERT INTO service_request_history
               (service_request_id, action, previous_status, new_status,
                performed_by, comment)
               VALUES ($1, 'status_change', $2, $3, $4, $5)""",
            request_id, current["status"], new_status, performed_by, comment
        )

        return await self.find_by_id(db, request_id)

    async def update_amounts(
        self,
        db: asyncpg.Connection,
        request_id: UUID,
        base_amount: float,
        supplements_amount: float,
        penalties_amount: float,
        total_amount: float
    ) -> None:
        """Update calculated amounts"""
        await db.execute(
            """UPDATE service_requests
               SET base_amount = $2, supplements_amount = $3,
                   penalties_amount = $4, total_amount = $5,
                   updated_at = NOW()
               WHERE id = $1""",
            request_id, base_amount, supplements_amount,
            penalties_amount, total_amount
        )

    async def update_extracted_data(
        self,
        db: asyncpg.Connection,
        request_id: UUID,
        extracted_data: Dict,
        extraction_confidence: float
    ) -> None:
        """Update extracted data from documents"""
        await db.execute(
            """UPDATE service_requests
               SET extracted_data = $2::jsonb, extraction_confidence = $3,
                   updated_at = NOW()
               WHERE id = $1""",
            request_id, json.dumps(extracted_data), extraction_confidence
        )

    async def assign_agent(
        self,
        db: asyncpg.Connection,
        request_id: UUID,
        agent_id: UUID,
        performed_by: UUID
    ) -> Dict:
        """Assign request to an agent"""
        await db.execute(
            """UPDATE service_requests
               SET assigned_to = $2, assigned_at = NOW(), updated_at = NOW()
               WHERE id = $1""",
            request_id, agent_id
        )

        await db.execute(
            """INSERT INTO service_request_history
               (service_request_id, action, performed_by, details)
               VALUES ($1, 'assigned', $2, $3)""",
            request_id, performed_by,
            json.dumps({"assigned_to": str(agent_id)})
        )

        return await self.find_by_id(db, request_id)

    async def schedule_cita(
        self,
        db: asyncpg.Connection,
        request_id: UUID,
        cita_date: str,
        cita_time: str,
        cita_location: str,
        performed_by: UUID
    ) -> Dict:
        """Schedule appointment (cita)"""
        await db.execute(
            """UPDATE service_requests
               SET cita_date = $2, cita_time = $3, cita_location = $4,
                   status = 'CITA_SCHEDULED', updated_at = NOW()
               WHERE id = $1""",
            request_id, cita_date, cita_time, cita_location
        )

        await db.execute(
            """INSERT INTO service_request_history
               (service_request_id, action, performed_by, details)
               VALUES ($1, 'cita_scheduled', $2, $3)""",
            request_id, performed_by,
            json.dumps({
                "cita_date": cita_date,
                "cita_time": cita_time,
                "cita_location": cita_location
            })
        )

        return await self.find_by_id(db, request_id)

    async def find_pending_assignment(
        self,
        db: asyncpg.Connection,
        entity_code: Optional[str] = None,
        limit: int = 50
    ) -> List[Dict]:
        """Find requests pending agent assignment"""
        if entity_code:
            query = """
                SELECT * FROM service_requests
                WHERE status = 'SUBMITTED' AND assigned_to IS NULL
                  AND entity_code = $1
                ORDER BY priority DESC, created_at ASC
                LIMIT $2
            """
            rows = await db.fetch(query, entity_code, limit)
        else:
            query = """
                SELECT * FROM service_requests
                WHERE status = 'SUBMITTED' AND assigned_to IS NULL
                ORDER BY priority DESC, created_at ASC
                LIMIT $1
            """
            rows = await db.fetch(query, limit)

        return [self._row_to_dict(row) for row in rows]

    async def find_by_agent(
        self,
        db: asyncpg.Connection,
        agent_id: UUID,
        status: Optional[str] = None,
        limit: int = 50,
        offset: int = 0
    ) -> List[Dict]:
        """Find requests assigned to an agent"""
        if status:
            query = """
                SELECT * FROM service_requests
                WHERE assigned_to = $1 AND status = $2
                ORDER BY priority DESC, created_at ASC
                LIMIT $3 OFFSET $4
            """
            rows = await db.fetch(query, agent_id, status, limit, offset)
        else:
            query = """
                SELECT * FROM service_requests
                WHERE assigned_to = $1
                ORDER BY priority DESC, created_at ASC
                LIMIT $2 OFFSET $3
            """
            rows = await db.fetch(query, agent_id, limit, offset)

        return [self._row_to_dict(row) for row in rows]

    async def update_verification_details(
        self,
        db: asyncpg.Connection,
        request_id: UUID,
        verification_details: Dict,
        verification_status: Optional[str] = None,
        performed_by: Optional[UUID] = None
    ) -> Dict:
        """
        Update verification_details (agent checklist) for a service request.
        Optionally update verification_status.
        """
        if verification_status:
            await db.execute(
                """UPDATE service_requests
                   SET verification_details = $2::jsonb,
                       verification_status = $3,
                       updated_at = NOW()
                   WHERE id = $1""",
                request_id, json.dumps(verification_details), verification_status
            )
        else:
            await db.execute(
                """UPDATE service_requests
                   SET verification_details = $2::jsonb,
                       updated_at = NOW()
                   WHERE id = $1""",
                request_id, json.dumps(verification_details)
            )

        # Create history entry if performed_by is provided
        if performed_by:
            await db.execute(
                """INSERT INTO service_request_history
                   (service_request_id, action, performed_by, details)
                   VALUES ($1, 'verification_updated', $2, $3)""",
                request_id, performed_by,
                json.dumps({"verification_details": verification_details})
            )

        return await self.find_by_id(db, request_id)

    async def get_workflow_config(
        self,
        db: asyncpg.Connection,
        workflow_code: str
    ) -> Optional[Dict]:
        """Get workflow configuration (form schema, checklist, etc.)"""
        row = await db.fetchrow(
            """SELECT code, name, config FROM workflows WHERE code = $1""",
            workflow_code
        )
        if not row:
            return None
        return {
            "code": row["code"],
            "name": row["name"],
            "config": row["config"] if isinstance(row["config"], dict) else json.loads(row["config"]) if row["config"] else {}
        }

    def _row_to_dict(self, row: asyncpg.Record) -> Dict:
        """Convert asyncpg Record to dict with proper JSON parsing"""
        if not row:
            return {}
        result = dict(row)
        # Parse JSONB fields
        for field in ["form_data", "extracted_data", "validations", "verification_details"]:
            if field in result and isinstance(result[field], str):
                result[field] = json.loads(result[field])
        return result


# Singleton instance
service_request_repository = ServiceRequestRepository()
