"""
Repository for service_requests table.
Data access layer following 3-tier architecture.
"""
import asyncpg
from typing import Optional, List, Dict, Any
from uuid import UUID
import json


class ServiceRequestRepository:
    """Data access layer for service_requests table"""

    async def create(
        self,
        db: asyncpg.Connection,
        user_id: UUID,
        workflow_code: str,
        solicitud_type: str = "expedicion",
        fiscal_service_id: Optional[int] = None,
        priority: str = "NORMAL",
        form_data: Optional[Dict] = None
    ) -> Dict:
        """
        Create new service request.
        Reference is auto-generated by database trigger (migration 020).
        """
        query = """
            INSERT INTO service_requests (
                user_id, workflow_code, solicitud_type,
                fiscal_service_id, priority, form_data, created_by
            )
            VALUES ($1, $2, $3, $4, $5, $6::jsonb, $1)
            RETURNING *
        """
        row = await db.fetchrow(
            query,
            user_id,
            workflow_code,
            solicitud_type,
            fiscal_service_id,
            priority,
            json.dumps(form_data) if form_data else '{}'
        )
        return self._row_to_dict(row)

    async def find_by_id(
        self,
        db: asyncpg.Connection,
        request_id: UUID
    ) -> Optional[Dict]:
        """Find service request by ID"""
        query = "SELECT * FROM service_requests WHERE id = $1"
        row = await db.fetchrow(query, request_id)
        return self._row_to_dict(row) if row else None

    async def find_by_reference(
        self,
        db: asyncpg.Connection,
        reference: str
    ) -> Optional[Dict]:
        """Find service request by reference (e.g., RES-2025-00001)"""
        query = "SELECT * FROM service_requests WHERE reference = $1"
        row = await db.fetchrow(query, reference)
        return self._row_to_dict(row) if row else None

    async def find_by_user(
        self,
        db: asyncpg.Connection,
        user_id: UUID,
        status: Optional[str] = None,
        workflow_code: Optional[str] = None,
        limit: int = 20,
        offset: int = 0
    ) -> List[Dict]:
        """List service requests for a user with optional filters"""
        conditions = ["user_id = $1"]
        params: List[Any] = [user_id]
        param_idx = 2

        if status:
            conditions.append(f"status = ${param_idx}")
            params.append(status)
            param_idx += 1

        if workflow_code:
            conditions.append(f"workflow_code = ${param_idx}")
            params.append(workflow_code)
            param_idx += 1

        where_clause = " AND ".join(conditions)
        params.extend([limit, offset])

        query = f"""
            SELECT * FROM service_requests
            WHERE {where_clause}
            ORDER BY created_at DESC
            LIMIT ${param_idx} OFFSET ${param_idx + 1}
        """
        rows = await db.fetch(query, *params)
        return [self._row_to_dict(row) for row in rows]

    async def count_by_user(
        self,
        db: asyncpg.Connection,
        user_id: UUID,
        status: Optional[str] = None
    ) -> int:
        """Count service requests for a user"""
        if status:
            query = "SELECT COUNT(*) FROM service_requests WHERE user_id = $1 AND status = $2"
            row = await db.fetchrow(query, user_id, status)
        else:
            query = "SELECT COUNT(*) FROM service_requests WHERE user_id = $1"
            row = await db.fetchrow(query, user_id)
        return row["count"]

    async def update_status(
        self,
        db: asyncpg.Connection,
        request_id: UUID,
        new_status: str,
        performed_by: UUID,
        comment: Optional[str] = None
    ) -> Dict:
        """
        Update status and create history entry.
        Uses service_request_history table for audit trail.
        """
        # Get current status
        current = await self.find_by_id(db, request_id)
        if not current:
            raise ValueError(f"Service request {request_id} not found")

        # Update status
        await db.execute(
            """UPDATE service_requests
               SET status = $2, updated_at = NOW()
               WHERE id = $1""",
            request_id, new_status
        )

        # Create history entry
        await db.execute(
            """INSERT INTO service_request_history
               (service_request_id, action, previous_status, new_status,
                performed_by, comment)
               VALUES ($1, 'status_change', $2, $3, $4, $5)""",
            request_id, current["status"], new_status, performed_by, comment
        )

        return await self.find_by_id(db, request_id)

    async def update_amounts(
        self,
        db: asyncpg.Connection,
        request_id: UUID,
        base_amount: float,
        supplements_amount: float,
        penalties_amount: float,
        total_amount: float
    ) -> None:
        """Update calculated amounts"""
        await db.execute(
            """UPDATE service_requests
               SET base_amount = $2, supplements_amount = $3,
                   penalties_amount = $4, total_amount = $5,
                   updated_at = NOW()
               WHERE id = $1""",
            request_id, base_amount, supplements_amount,
            penalties_amount, total_amount
        )

    async def update_extracted_data(
        self,
        db: asyncpg.Connection,
        request_id: UUID,
        extracted_data: Dict,
        extraction_confidence: float
    ) -> None:
        """Update extracted data from documents"""
        await db.execute(
            """UPDATE service_requests
               SET extracted_data = $2::jsonb, extraction_confidence = $3,
                   updated_at = NOW()
               WHERE id = $1""",
            request_id, json.dumps(extracted_data), extraction_confidence
        )

    async def assign_agent(
        self,
        db: asyncpg.Connection,
        request_id: UUID,
        agent_id: UUID,
        performed_by: UUID
    ) -> Dict:
        """Assign request to an agent"""
        await db.execute(
            """UPDATE service_requests
               SET assigned_to = $2, assigned_at = NOW(), updated_at = NOW()
               WHERE id = $1""",
            request_id, agent_id
        )

        await db.execute(
            """INSERT INTO service_request_history
               (service_request_id, action, performed_by, details)
               VALUES ($1, 'assigned', $2, $3)""",
            request_id, performed_by,
            json.dumps({"assigned_to": str(agent_id)})
        )

        return await self.find_by_id(db, request_id)

    async def schedule_cita(
        self,
        db: asyncpg.Connection,
        request_id: UUID,
        cita_date: str,
        cita_time: str,
        cita_location: str,
        performed_by: UUID
    ) -> Dict:
        """Schedule appointment (cita)"""
        await db.execute(
            """UPDATE service_requests
               SET cita_date = $2, cita_time = $3, cita_location = $4,
                   status = 'CITA_SCHEDULED', updated_at = NOW()
               WHERE id = $1""",
            request_id, cita_date, cita_time, cita_location
        )

        await db.execute(
            """INSERT INTO service_request_history
               (service_request_id, action, performed_by, details)
               VALUES ($1, 'cita_scheduled', $2, $3)""",
            request_id, performed_by,
            json.dumps({
                "cita_date": cita_date,
                "cita_time": cita_time,
                "cita_location": cita_location
            })
        )

        return await self.find_by_id(db, request_id)

    async def find_pending_assignment(
        self,
        db: asyncpg.Connection,
        entity_code: Optional[str] = None,
        limit: int = 50
    ) -> List[Dict]:
        """Find requests pending agent assignment"""
        if entity_code:
            query = """
                SELECT * FROM service_requests
                WHERE status = 'SUBMITTED' AND assigned_to IS NULL
                  AND entity_code = $1
                ORDER BY priority DESC, created_at ASC
                LIMIT $2
            """
            rows = await db.fetch(query, entity_code, limit)
        else:
            query = """
                SELECT * FROM service_requests
                WHERE status = 'SUBMITTED' AND assigned_to IS NULL
                ORDER BY priority DESC, created_at ASC
                LIMIT $1
            """
            rows = await db.fetch(query, limit)

        return [self._row_to_dict(row) for row in rows]

    async def find_by_agent(
        self,
        db: asyncpg.Connection,
        agent_id: UUID,
        status: Optional[str] = None,
        limit: int = 50,
        offset: int = 0
    ) -> List[Dict]:
        """Find requests assigned to an agent"""
        if status:
            query = """
                SELECT * FROM service_requests
                WHERE assigned_to = $1 AND status = $2
                ORDER BY priority DESC, created_at ASC
                LIMIT $3 OFFSET $4
            """
            rows = await db.fetch(query, agent_id, status, limit, offset)
        else:
            query = """
                SELECT * FROM service_requests
                WHERE assigned_to = $1
                ORDER BY priority DESC, created_at ASC
                LIMIT $2 OFFSET $3
            """
            rows = await db.fetch(query, agent_id, limit, offset)

        return [self._row_to_dict(row) for row in rows]

    async def update_verification_details(
        self,
        db: asyncpg.Connection,
        request_id: UUID,
        verification_details: Dict,
        verification_status: Optional[str] = None,
        performed_by: Optional[UUID] = None
    ) -> Dict:
        """
        Update verification_details (agent checklist) for a service request.
        Optionally update verification_status.
        """
        if verification_status:
            await db.execute(
                """UPDATE service_requests
                   SET verification_details = $2::jsonb,
                       verification_status = $3,
                       updated_at = NOW()
                   WHERE id = $1""",
                request_id, json.dumps(verification_details), verification_status
            )
        else:
            await db.execute(
                """UPDATE service_requests
                   SET verification_details = $2::jsonb,
                       updated_at = NOW()
                   WHERE id = $1""",
                request_id, json.dumps(verification_details)
            )

        # Create history entry if performed_by is provided
        if performed_by:
            await db.execute(
                """INSERT INTO service_request_history
                   (service_request_id, action, performed_by, details)
                   VALUES ($1, 'verification_updated', $2, $3)""",
                request_id, performed_by,
                json.dumps({"verification_details": verification_details})
            )

        return await self.find_by_id(db, request_id)

    async def get_workflow_config(
        self,
        db: asyncpg.Connection,
        workflow_code: str
    ) -> Optional[Dict]:
        """Get workflow configuration (form schema, checklist, etc.)"""
        row = await db.fetchrow(
            """SELECT code, name, config FROM workflows WHERE code = $1""",
            workflow_code
        )
        if not row:
            return None
        return {
            "code": row["code"],
            "name": row["name"],
            "config": row["config"] if isinstance(row["config"], dict) else json.loads(row["config"]) if row["config"] else {}
        }

    # =========================================================================
    # HISTORY METHODS
    # =========================================================================

    async def get_request_history(
        self,
        db: asyncpg.Connection,
        request_id: UUID,
        action_types: Optional[List[str]] = None,
        from_date: Optional[str] = None,
        to_date: Optional[str] = None,
        include_system: bool = True,
        include_ocr: bool = True,
        include_assignments: bool = True,
        limit: int = 50,
        offset: int = 0
    ) -> tuple[List[Dict], int]:
        """
        Get full consolidated history timeline for a service request.

        Combines data from:
        - service_request_history (status changes, document uploads, etc.)
        - gemini_processing_logs (OCR processing results)
        - assignments (agent assignments and reassignments)

        Args:
            db: Database connection
            request_id: Service request UUID
            action_types: Filter by action types (e.g., ['status_change', 'document_added'])
            from_date: Filter from date (ISO format)
            to_date: Filter to date (ISO format)
            include_system: Include system-initiated actions (performed_by IS NULL)
            include_ocr: Include OCR processing logs
            include_assignments: Include assignment history
            limit: Max entries to return
            offset: Pagination offset

        Returns:
            Tuple of (list of history entries, total count)
        """
        # Build date conditions for all queries
        date_conditions = []
        date_params: List[Any] = []
        date_param_idx = 2  # $1 is request_id

        if from_date:
            date_conditions.append(f"performed_at >= ${date_param_idx}")
            date_params.append(from_date)
            date_param_idx += 1

        if to_date:
            date_conditions.append(f"performed_at <= ${date_param_idx}")
            date_params.append(to_date)
            date_param_idx += 1

        date_filter = " AND " + " AND ".join(date_conditions) if date_conditions else ""

        # Build action type filter
        action_filter = ""
        if action_types:
            action_filter = f" AND action = ANY(${date_param_idx})"
            date_params.append(action_types)
            date_param_idx += 1

        # System filter
        system_filter = "" if include_system else " AND performed_by IS NOT NULL"

        # Build UNION query for consolidated history
        union_parts = []

        # Part 1: service_request_history
        union_parts.append(f"""
            SELECT
                srh.id::text as id,
                srh.action,
                srh.previous_status,
                srh.new_status,
                srh.details,
                srh.comment,
                srh.performed_at,
                srh.performed_by,
                'history' as source,
                u.id as performer_id,
                COALESCE(u.full_name, u.first_name || ' ' || u.last_name) as performer_name,
                u.email as performer_email,
                u.role as performer_role
            FROM service_request_history srh
            LEFT JOIN users u ON u.id = srh.performed_by
            WHERE srh.service_request_id = $1{date_filter}{action_filter}{system_filter}
        """)

        # Part 2: gemini_processing_logs (OCR)
        if include_ocr:
            # OCR logs don't have action types in the filter
            ocr_date_filter = date_filter.replace("performed_at", "created_at")
            union_parts.append(f"""
                SELECT
                    gpl.id::text as id,
                    CASE
                        WHEN gpl.has_error THEN 'ocr_failed'
                        ELSE 'ocr_completed'
                    END as action,
                    NULL as previous_status,
                    NULL as new_status,
                    jsonb_build_object(
                        'document_code', gpl.document_code,
                        'document_name', gpl.document_name,
                        'extraction_confidence', gpl.extraction_confidence,
                        'risk_level', gpl.risk_level,
                        'risk_score', gpl.risk_score,
                        'processor', gpl.processor,
                        'processing_time_ms', gpl.processing_time_ms,
                        'fields_extracted', gpl.fields_extracted,
                        'fields_missing', gpl.fields_missing,
                        'has_error', gpl.has_error,
                        'error_message', gpl.error_message
                    ) as details,
                    CASE
                        WHEN gpl.has_error THEN gpl.error_message
                        ELSE NULL
                    END as comment,
                    gpl.created_at as performed_at,
                    gpl.user_id as performed_by,
                    'ocr' as source,
                    u.id as performer_id,
                    COALESCE(u.full_name, u.first_name || ' ' || u.last_name) as performer_name,
                    u.email as performer_email,
                    u.role as performer_role
                FROM gemini_processing_logs gpl
                LEFT JOIN users u ON u.id = gpl.user_id
                WHERE gpl.service_request_id = $1{ocr_date_filter}
            """)

        # Part 3: assignments
        if include_assignments:
            assign_date_filter = date_filter.replace("performed_at", "assigned_at")
            union_parts.append(f"""
                SELECT
                    a.id::text as id,
                    CASE
                        WHEN a.reassigned_at IS NOT NULL THEN 'reassigned'
                        ELSE 'assigned'
                    END as action,
                    NULL as previous_status,
                    a.status::text as new_status,
                    jsonb_build_object(
                        'assignment_method', a.assignment_method::text,
                        'priority_level', a.priority_level,
                        'deadline', a.deadline,
                        'reassignment_reason', a.reassignment_reason::text,
                        'reassignment_notes', a.reassignment_notes,
                        'agent_name', COALESCE(agent_user.full_name, agent_user.first_name || ' ' || agent_user.last_name),
                        'reassigned_to_name', COALESCE(reassign_user.full_name, reassign_user.first_name || ' ' || reassign_user.last_name)
                    ) as details,
                    a.notes as comment,
                    COALESCE(a.reassigned_at, a.assigned_at) as performed_at,
                    COALESCE(a.assigned_by_profile_id, a.agent_profile_id) as performed_by,
                    'assignment' as source,
                    assigner.id as performer_id,
                    COALESCE(assigner.full_name, assigner.first_name || ' ' || assigner.last_name) as performer_name,
                    assigner.email as performer_email,
                    assigner.role as performer_role
                FROM assignments a
                LEFT JOIN ministry_agents ma ON ma.id = a.agent_profile_id
                LEFT JOIN users agent_user ON agent_user.id = ma.user_id
                LEFT JOIN ministry_agents ma_reassign ON ma_reassign.id = a.reassigned_to_profile_id
                LEFT JOIN users reassign_user ON reassign_user.id = ma_reassign.user_id
                LEFT JOIN ministry_agents ma_assigner ON ma_assigner.id = COALESCE(a.assigned_by_profile_id, a.agent_profile_id)
                LEFT JOIN users assigner ON assigner.id = ma_assigner.user_id
                WHERE a.item_id = $1 AND a.item_type = 'service_request'{assign_date_filter}
            """)

        union_query = " UNION ALL ".join(union_parts)

        # Count total
        count_query = f"""
            SELECT COUNT(*) as total FROM ({union_query}) consolidated
        """
        all_params = [request_id] + date_params
        count_row = await db.fetchrow(count_query, *all_params)
        total = count_row["total"] if count_row else 0

        # Get paginated entries
        final_query = f"""
            SELECT * FROM ({union_query}) consolidated
            ORDER BY performed_at DESC
            LIMIT ${len(all_params) + 1} OFFSET ${len(all_params) + 2}
        """
        all_params.extend([limit, offset])
        rows = await db.fetch(final_query, *all_params)

        entries = []
        for row in rows:
            entry = {
                "id": row["id"],
                "action": row["action"],
                "previous_status": row["previous_status"],
                "new_status": row["new_status"],
                "details": row["details"] if isinstance(row["details"], dict) else json.loads(row["details"]) if row["details"] else {},
                "comment": row["comment"],
                "performed_at": row["performed_at"].isoformat() if row["performed_at"] else None,
                "source": row["source"],
                "performed_by": None
            }

            # Add performer info if available
            if row["performer_id"]:
                entry["performed_by"] = {
                    "user_id": str(row["performer_id"]),
                    "full_name": row["performer_name"],
                    "email": row["performer_email"],
                    "role": row["performer_role"],
                    "is_system": False
                }
            elif row["performed_by"] is None:
                entry["performed_by"] = {
                    "user_id": None,
                    "full_name": "Sistema",
                    "email": None,
                    "role": "system",
                    "is_system": True
                }

            entries.append(entry)

        return entries, total

    async def get_request_with_history_summary(
        self,
        db: asyncpg.Connection,
        request_id: UUID
    ) -> Optional[Dict]:
        """
        Get service request with history summary statistics.

        Returns request data plus:
        - total_status_changes
        - total_documents
        - total_assignments
        - first_action_at
        - last_action_at
        """
        query = """
            SELECT
                sr.*,
                COALESCE(u.full_name, u.first_name || ' ' || u.last_name, u.email) as citizen_name,
                -- History stats
                (SELECT COUNT(*) FROM service_request_history WHERE service_request_id = sr.id AND action = 'status_change') as total_status_changes,
                (SELECT COUNT(*) FROM service_request_history WHERE service_request_id = sr.id AND action = 'document_added') as total_documents,
                (SELECT COUNT(*) FROM service_request_history WHERE service_request_id = sr.id AND action IN ('assigned', 'reassigned')) as total_assignments,
                (SELECT MIN(performed_at) FROM service_request_history WHERE service_request_id = sr.id) as first_action_at,
                (SELECT MAX(performed_at) FROM service_request_history WHERE service_request_id = sr.id) as last_action_at
            FROM service_requests sr
            JOIN users u ON u.id = sr.user_id
            WHERE sr.id = $1
        """
        row = await db.fetchrow(query, request_id)
        if not row:
            return None

        result = self._row_to_dict(row)
        result["citizen_name"] = row["citizen_name"]
        result["total_status_changes"] = row["total_status_changes"] or 0
        result["total_documents"] = row["total_documents"] or 0
        result["total_assignments"] = row["total_assignments"] or 0
        result["first_action_at"] = row["first_action_at"].isoformat() if row["first_action_at"] else None
        result["last_action_at"] = row["last_action_at"].isoformat() if row["last_action_at"] else None
        return result

    async def get_history_list_for_entity(
        self,
        db: asyncpg.Connection,
        workflow_codes: List[str],
        status_filter: Optional[str] = None,
        limit: int = 20,
        offset: int = 0,
        assigned_to_user_id: Optional[UUID] = None
    ) -> tuple[List[Dict], int]:
        """
        Get list of requests with history summary for an entity.
        Used by the history list page.

        Args:
            db: Database connection
            workflow_codes: List of workflow codes for the entity
            status_filter: Optional status filter
            limit: Max items to return
            offset: Pagination offset
            assigned_to_user_id: If provided, filter by assigned_to (for agent access control)

        Returns:
            Tuple of (list of summary items, total count)
        """
        conditions = ["sr.workflow_code = ANY($1)"]
        params: List[Any] = [workflow_codes]
        param_idx = 2

        if status_filter:
            conditions.append(f"sr.status = ${param_idx}")
            params.append(status_filter)
            param_idx += 1

        # Access control: filter by assigned agent if provided
        if assigned_to_user_id is not None:
            conditions.append(f"sr.assigned_to = ${param_idx}")
            params.append(assigned_to_user_id)
            param_idx += 1

        where_clause = " AND ".join(conditions)

        # Count total
        count_query = f"""
            SELECT COUNT(*) as total
            FROM service_requests sr
            WHERE {where_clause}
        """
        count_row = await db.fetchrow(count_query, *params)
        total = count_row["total"] if count_row else 0

        # Get items with last action info
        params.extend([limit, offset])
        query = f"""
            SELECT
                sr.id,
                sr.reference,
                sr.workflow_code,
                sr.status,
                sr.created_at,
                COALESCE(u.full_name, u.first_name || ' ' || u.last_name, u.email) as citizen_name,
                -- Last action info
                last_history.action as last_action,
                last_history.performed_at as last_action_at,
                COALESCE(last_performer.full_name, last_performer.first_name || ' ' || last_performer.last_name, 'Sistema') as last_performer,
                -- Total actions
                (SELECT COUNT(*) FROM service_request_history WHERE service_request_id = sr.id) as total_actions
            FROM service_requests sr
            JOIN users u ON u.id = sr.user_id
            LEFT JOIN LATERAL (
                SELECT action, performed_at, performed_by
                FROM service_request_history
                WHERE service_request_id = sr.id
                ORDER BY performed_at DESC
                LIMIT 1
            ) last_history ON true
            LEFT JOIN users last_performer ON last_performer.id = last_history.performed_by
            WHERE {where_clause}
            ORDER BY COALESCE(last_history.performed_at, sr.created_at) DESC
            LIMIT ${param_idx} OFFSET ${param_idx + 1}
        """
        rows = await db.fetch(query, *params)

        items = []
        for row in rows:
            days_since = (row["created_at"].date() - row["created_at"].date()).days if row["created_at"] else 0
            last_action_at = row["last_action_at"]
            is_stale = False
            if last_action_at:
                from datetime import datetime, timezone
                now = datetime.now(timezone.utc)
                if last_action_at.tzinfo is None:
                    from datetime import timezone as tz
                    last_action_at = last_action_at.replace(tzinfo=tz.utc)
                is_stale = (now - last_action_at).days >= 7

            items.append({
                "request_id": str(row["id"]),
                "reference": row["reference"] or "",
                "workflow_code": row["workflow_code"],
                "citizen_name": row["citizen_name"] or "N/A",
                "current_status": row["status"],
                "last_action": row["last_action"] or "status_change",
                "last_action_at": row["last_action_at"].isoformat() if row["last_action_at"] else None,
                "last_performer": row["last_performer"],
                "total_actions": row["total_actions"] or 0,
                "days_since_created": days_since,
                "is_stale": is_stale
            })

        return items, total

    def _row_to_dict(self, row: asyncpg.Record) -> Dict:
        """Convert asyncpg Record to dict with proper JSON parsing"""
        if not row:
            return {}
        result = dict(row)
        # Parse JSONB fields
        for field in ["form_data", "extracted_data", "validations", "verification_details"]:
            if field in result and isinstance(result[field], str):
                result[field] = json.loads(result[field])
        return result


# Singleton instance
service_request_repository = ServiceRequestRepository()
